plugins/nscd/nscd_

A plugin to monitor nscd databases.

Added nscd plugin

---

plugins/varnish4/README.md

* reflects changes of @ssm (commit c4c0a9872c, 5 Oct 2014)
* added path and command examples for installation

small update of README.md

---

plugins/snmp/snmp__rms2_

supports temperature and contact sensor types; humidity sensors should work too but are untested since I have none.

new plugin for monitoring Knuerr RMS Compact II rack monitoring units

---

plugins/ejabberd/ejabberd_resources_/ejabberd_resources_
plugins/network/ping/ping

* add mnesia support to ejabberd
* use erl_call instead of hacky erl -c
* fix ping plugin logic

Update jabber/network plugins

---

plugins/ftp/vsftpd

- Allow log file path to be configured via plugin-conf.d env.logfile
- Add counters for successful and failed renames
- Switch to use DERIVE and min 0 to fix problems during rotation and show request counts per period
- Improve performance for large log files by using awk

Improve vsftpd plugin

---

plugins/unicorn/unicorn_memory_status
plugins/unicorn/unicorn_status

User to be able to the pid name change.
default is `unicorn.pid`, but can be changed
use `env.pid_name my_unicorn.pid`

unicorn_memory_status/unicorn_status change pid name

---

plugins/backup/backup.sh

If you have a directory where daily, weekly, monthly you generate
backups of files, SQL databases, etc, you might want to be informed
if the backup generation process is gone or the behavior changes
greatly. This monitoring plugin watches the number of young files
in a certain directory. Relies on find command to do the job.

General purpose backup monitoring plugin

---

plugins/php/php_opcache
plugins/php/php_opcache.php

Now the sum and AREA is always the total assigned memory

Add wasted memory to the graph

---

plugins/mongodb/mongo_collection_

Modified version of plugins from https://github.com/pcdummy/mongomon that composes all the plugins into one script.
It works fine, but still leaves a room for future improvement if anyone is interested.

mongo_collection_ to track per-database statistics

---

plugins/unicorn/unicorn_

`grep "unicorn worker` is unicorn_rails process not match.
I want to match the `unicorn` or 'unicorn_rails'

unicorn_ "unicorn_rails" process not working

---

plugins/network/modem-nvg510

Tracks most stats reported from NVG510 DSL modems

Add modem-nvg510

---

plugins/system/multicpu1sec/.gitignore
plugins/system/multicpu1sec/multicpu1sec-c.c

This contains various optimisations :
* Using POSIX calls instead of stdlib ones
* Keep the various files open

Multicpu1sec c optimsations

---

plugins/snmp/snmp__cisco_sbs_cpu

Monitors CPU % Utilization on Cisco Small Business Devices (Does not use the typical Cisco iOS OIDs)

Plugin monitoring CPU on Cisco SB Devices

---

plugins/network/radio

Updated to match the outputs of current ice- and shoutcast versions...

Updated to v0.2

---

plugins/network/arp_bsd_
plugins/network/pf_tables_

Inout: bandwidth usage for table
Addresses: number of entries in table

pf_tables : Munin plugin to monitor pf tables.

---

plugins/zfs/zfs-filesystem-graph

with env the script is running with linux and bsd

Update zfs-filesystem-graph: using env

---

plugins/balanceng/bng

The script fetches the data from bng's SNMP interface and thus dynamicly
adapts to bng's configuration.  This means that no further configuration
is needed after enabling the plugin.

munin plugin for BalanceNG

---

plugins/system/1sec/if1sec-c.c

They are written in C, as low overhead is the main design point.

Adding 1sec system plugins C for linux

---

plugins/hhvm/hhvm_

This params in new hhvm version doesnt work any more.

Remove old params

---

plugins/docker/docker_cpu
plugins/docker/docker_memory

The plugin breaks when a container gets in a weird state. Fixing the problem ignoring containers without the proc pseudo-files.

Docker Plugin: Bugfix.

---

plugins/apache/apache_average_time_last_n_requests

Possibility to manage distinct log files

apache_average_time_last_n_requests: multi-vhosts

---

plugins/rethinkdb/rethinkdb_node_io

one graph with read/write docs and overall requests

Add basic support for RethinkDB

---

plugins/disk/lvm_
plugins/disk/lvm_snap_used

* lvm_: only add clean_fieldname
* lvm_snap_used
* add clean_fieldname
* force y-axis scale to 0-100 %

fix - add clean_fieldname to make field name safe

---

plugins/system/hugepages

Readd Anonymous Hugepages (aka. Transparent Hugepages) to system/hugepage plugin. This reverts part of the changes by Mrten in #308...

Readd Anonymous Hugepages to system/hugepage

---

plugins/system/cpubyuser

Add ALL keyword to count cpu use of all users. May be a dirty hack, but not sure how to do this otherwise...

ALL keyword

---

plugins/network/olsrd

Collect basic information about the neighbours of an OLSR node:
* link quality
* neighbour link quality
* number of nodes reachable behind each neighbour
* ping times of direct neighbours
OLSR is a routing protocol (layer 3).

new network plugin added: olsrd

---

plugins/disk/btrfs_subvol_usage

Plugin to monitor usage of subvolumes on a BTRFS filesystem.

add btrfs_subvol_usage plugin

---

plugins/network/pf_tables_

- Fix matching table names that include "-" charachter
- Fix drawing graph for inout graphs

Fix fieldname matching and correctly draw inout graphs [pf_table_ plugin]

---

plugins/system/memory_by_process

memory_by_process: try to be smarted about labels and cleanup field names more deeply

memory_by_process: try to be smarted about labels and cleanup field names more deeply

---

plugins/boinc/boinc_projs

the problem was introduced in 1568bf67ea34b1ae59d3846a66f106ebce5702a4

[boinc_projs] fix typo

---

plugins/sickbeard/sickbeard_episodes

[sickbeard_episodes] Report snatched episodes

---

plugins/lxd/lxd_disk

stopped containers have no disk space info and the plugin crashed. Now
it only shows disk usage for running containers

fixed lxd_disk for stopped containers

---

plugins/senderbase/senderbase

This adds a plugin for the SenderBase email server reputation service.

SenderBase Plugin

---

plugins/system/cpubyuser

* fieldname cleaning
* "no" output for autoconf
* fix "ALL" expansion for "config"
* fix handling of long usernames
* switch from bash to sh

[cpubyuser] fix various issues

---

plugins/mpd/mpdstats_

* fix #576 (unsupported netcat parameter)
* use `which` for netcat detection
* allow unconfigured usage (print all stats)

Improve mpdstats

---

plugins/munin/munin_events

munin_events - Plugin to monitor munin update log

Added munin_events plugin

---

plugins/monit/monit_parser

* implemented  python3 compatibility (it still runs with python2)
* documentation added (Closes: 548)
* memory allocation values are parsed properly now (previously broken values may jump by a factor of 1024)

Improve monit parser

---

plugins/network/upnpc_
plugins/upnpc/upnpc_

[plugins/upnpc_] Add upnpc-based router monitoring plugin

---

plugins/system/file_length_

[file_length_] A versatile plugin to count the lines in specified files

---

plugins/system/deborphan

Signed-off-by: Olivier Mehani shtrom@ssji.net

[deborphan] New plugin counting orphaned packages in all sections

---

plugins/mongodb/mongo_collection_
plugins/mongodb/mongo_lag

https://api.mongodb.com/python/current/changelog.html#mongoclient-changes

Fix for pymongo > 3.0 and connection support of MongoClient only

---

plugins/processes/proc_mem_by_user

- use of bash
- don't corrupt rrd files when "root" (or any unclean value) is requested

proc_mem_by_user:

---

plugins/network/mtr100_

The value of the first hop is undefined, but includes the source's hostname for comparison with other graphs generated for traceroutes to the same target.

Add source as first 'hop'

---

plugins/zfs/zfsonlinux_stats_

https://github.com/munin-monitoring/contrib/issues/680

Pass over empty lines in the arcstats

---

plugins/sge/sge_job_stats

job stats (running/queued/submitted) for gridengine

Add job stats graph

---

plugins/time/chrony

*  rewrite field handling (Closes: #446)
*  use "which" for "chronyc" location
*  switch from "bash" to "sh"
*  fix exit code of failing "autoconf"

[chrony] various improvements

---

plugins/system/debsecan

Also, generally cleanup the code of the plugin.

[debsecan] Flag remotely exploitable CVEs separately

---

plugins/snmp/snmp__gwia_bytes_
plugins/snmp/snmp__gwia_msgs_
plugins/snmp/snmp__gwmta_msgs_
plugins/snmp/snmp__gwpoa_

Category Tree: Reduce number of categories

---

plugins/network/multibandwidth

Plugin to monitor the bandwidth between localhost and serveral hosts.

multibandwidth

---

plugins/dspam/dspam_

ref: https://github.com/munin-monitoring/contrib/issues/828

dspam_ : fix parsing error when values are huge

---

plugins/dspam/dspam_

- typo
- cleaning invalid lockfile
- new graph relprocessed in messages / minute

dspam_ fixes

---

plugins/solaris/io_disk

Hello,
I would like to add dirtyconfig and make some changes of code style for Solaris io_disk plugin. Please consider this pull request.

Add dirtyconfig for Solaris io_disk plugin

---

plugins/currency/nanopool/nanopool_

Hello!
I've added a plugin to monitor the most important result data of Nanopool ethereum mining. It shows the hashrate, average hashrate, total balance and the worker data with their hashrate and number of shares per minute. 
Thanks in advance & kind regards,
Ralf

New plugin to get result data of Nanopool ethereum mining pool.

---

plugins/oracle/oracle_sysstat

I have updated oracle_sysstat plugin. 
- Fix to work autoconf.
- Cleanup code.
Please consider this pull request. Thanks.

Update oracle_sysstat plugin

---

plugins/printer/snmp__hpclj

Provides consumption levels for HP LaserJet Printers.
Now with multigraph support in a single pull. ;)

New SNMP Plugin for HP LaserJet Printers

---

plugins/snmp/snmp__cyberpower

Plugin to monitor status & environment readings readings for CyberPower UPS units with an RMCARD202 module.
Cleaned-up version as Multigraph-Plugin. ;)

SNMP Plugin for CyberPower UPS

---

plugins/libvirt/kvm_cpu
plugins/libvirt/kvm_io
plugins/libvirt/kvm_mem
plugins/libvirt/kvm_net

Fixes issues with kvm on debian jessie/proxmox5.

Fix kvm_ plugins

---

plugins/wifi/wifi_signal

trivial change, needed to have  the right marker to enable autoconf

update wifi_signal to correct a typo

---

plugins/gpu/nvidia_gpu_

I cleaned up `nvidia_gpu_` a bit and implemented ShellCheck recommendations.
Then I implemented a new graph for GPU utilization. Tested with two GTX 1080 using driver version 390.25.

Nvidia GPU utilization

---

plugins/jenkins/jenkins_
plugins/jenkins/jenkins_nodes_

Added recursion into folders for jenkins_
Fixed boolean check in jenkins_node 
Tested on Jenkins 1 and working.

Folder recursion and offline fix for jenkins plugin

---

.travis.yml
t/test.t

slowly introduce "shellcheck" into the tests (there are only a few ksh scripts)

tests: add "shellcheck" tests for "ksh" scripts

---

README.md
plugins/README.md

* add more hints for plugin contributors
* outline purpose of the repository
* describe directory layout

move plugin documentation to separate README

---

plugins/weather/openweather_

Add missing ``appid`` in http request and rename env to avoid collision with potential other api key.

Add missing appid in URL

---

templates/munstrap/templates/munin-overview.tmpl

Remove item 'lastTag:tabs' on index page. It resolved issue #884

Resolved issue 884 with munstrap tabid

---

plugins/currency/zcash/zcash_flypool_hashrate_

Hi,
I wrote a new plugin for cryptocurrency Zcash (ZEC). With this plugin you can monitor your miner hashrate.
Earlier comments of my Ethereum plugins were considered:
https://github.com/munin-monitoring/contrib/pull/851
Sample:
https://imgur.com/gFws4Hc
Best regards
Nils

Plugin to get hashrate of Flypool Zcash mining pool

---

plugins/lxc/lxc_proc
plugins/lxc/lxc_ram

- add Ubuntu 14.04 support for lxc_proc
- add new graph draw type option for lxc_ram
- example: https://github.com/mittyorz/munin-plugins/wiki/LXC#envareastack

Ubuntu 14.04 support, new graph option

---

plugins/ceph/ceph_osd
plugins/jvm/jstat__gccount
plugins/jvm/jstat__gctime
plugins/jvm/jstat__heap

* simplify handling of environment settings
* improve detection of default JAVA_HOME
* mention "graphtitle" setting in documentation
* simplify handling of different JVM types
* add support for Java 1.8
* fix shellcheck issues
* switch from bash to sh
* add format examples

jstat plugins: various improvements

---

plugins/mysql/mysql_slave_threads

Add error message from mysql to extinfo

Improve plugin mysql_slave_thread

---

plugins/zfs/zfs_list

#969 zfs/zfs_list: Add support for dash in zfs_list

Add support for dash in zfs_list

---

plugins/system/file_length_

[file_length_] Generic plugin to monitor the number of lines (or variation thereof) of arbitrary files

---

plugins/chrony/chrony_drift

This commit adds a plugin for `chronyd driftfile` .

Add chrony_drift.

---

plugins/ntp/ntp_drift

This commit adds a plugin for `ntpd driftfile` .

Add ntp_drift.

---

plugins/router/bbox

The UI isn't compatible anymore.

bbox: upgrade bbox version.

---

plugins/redis/redis_

Added Redis replication backlog graph

Added Redis replication backlog graph

---

plugins/disk/nvme

This is a multigraph plugin which makes three graphs, nvme_usage, nvme_bytes and nvme_writecycles.  See POD below for details.

nvme - Munin plugin to monitor the use of NVMe devices

---

plugins/currency/bitcoin/bitcoind_

* reformat documentation header
* migrate to python3
* introduce explicit setting for configuration file

Plugin bitcoind improvements

---

plugins/jenkins/jenkins_

Merge the two "multilevel jobs" proposals for the jenkins plugin:
* #883: recursively request jobs on demand (was merged before)
* #881: process all jobs up to a defined nesting level in a single request (not merged, yet)

Jenkins multilevel jobs

---

plugins/ssl/ssl-certificate-expiry

Also, cleanup the script to be better POSIX sh compatible, and add -u to
the shebang.

[ssl-certificate-expiry] Add asynchronous update via cron

---

plugins/php/php_fpm_process

Breaking changes:
* php_fpm_slowrequests is superseded by php_fpm_requests

[php_fpm_process] Add queue and request information

---

plugins/zfs/zpool_capacity

zpool_capacity:  Added fragmentation % graph

---

plugins/disk/megaraid-controller-information

Update megaraid-controller-information to support "megacli" executable name 

---

plugins/ssl/certificate_file_expiry
plugins/ssl/letsencrypt_weekly

* plugin to monitor certificiate lifetime
* plugin to monitor letsencrypt certificate issue limit

Plugins for certificates

---

plugins/asterisk/asterisk

This patch set should make the asterisk multi-graph plugin work again on recent versions of Asterisk.

Fix asterisk ami parsing

---

.travis.yml
plugins/amr/amr

just for working branch for improving and testing the travis CI

WIP: Travis Tests

---

plugins/router/arris-tg3442

MUNIN Plugin to monitor status of Arris TG3442 / TG2492LG-85 and compatible cable modems

DOCSIS status monitoring

---

plugins/raspberry-pi/w1_

Plugin to graph the output of 1-Wire DS1820 temperature sensors on the Raspberry PI

w1_ plugin

---

plugins/ssl/certificate_file_expiry

Typos broke the sample configuration

Fix typos in certificate_file_expiry

---

plugins/mongodb/mongo_lag

Fix mongo_lag plugin and add auth feature

Mongo lag upgrade

---

plugins/relayd/relayd

Hi,
Here's two small bug fixes for the relayd plugin.

Relayd fixes

---

plugins/prosody/prosody_

- Encode telnet commands because [telnetlib only accept bytes](https://docs.python.org/3/library/telnetlib.html#telnetlib.Telnet.write)
- Resolved #954 with proposed regex

Fix prosody plugin by encoding telnetlib commands

---

plugins/docker/docker_

Based on `docker` Python package to talk to the Docker socket.
Fix:
- CPU
- Memory
Add:
- Containers number
- Containers status
- Images number
- Volumes number
Fix #1027

Rewrite docker plugin

---

plugins/freeradius/freeradius_sqlippools_

Uses the generic Perl DBI interface, requiring the user to specify a driver and
provide the corresponding DBD module.

Plugin freeradius_sqlippool_: New plugin to show IP pool utilisation

---

plugins/network/netstat_s_

* quick fix
* if this "typo" was intentional ignore this PR
Signed-off-by: corbolais <corbolais@gmail.com>

typo: retransmited -> retransmitted

---

plugins/twemproxy/nutcracker_requests_

twemproxy: add python3 support

---

plugins/jitsi_videobridge/jitsi_videobridge

Simple multigraph plugin with one graph for current session infos and one
graph for total conferences created.

Add jitsi-videobridge plugin

---

plugins/nextcloud/nextcloud_

A simple nextcloud multigraph plugin.

Add nextcloud_ plugin

---

plugins/router/freebox

[router/freebox] fix vlabel

---

plugins/currency/bitcoin/bitcoind_

* Use new RPC calls to get relevant statistics, as some calls are either
deprecated or completely removed.
* Fix response printing when MUNIN_DEBUG is set.
* Remove "fees" graph as there is no sane way to implement that.
Closes #995

bitcoind_: update for Bitcoin Core v0.19.0 release

---

plugins/user/procbyuser

Graphs the number of processes owned by a user over time

[plugins/user/procbyuser] Added plugin to monitor processes of a user

---

plugins/mysql/mysql_disk_by_prefix

The `mysql_size_*` scripts list the size per database, not per user

[plugins/mysql/mysql_disk_by_prefix] Add plugin for DB size by prefix

---

plugins/dovecot/dovecot

[plugins/dovecot/dovecot] Make 'connected users' graph DERIVEable

---

plugins/user/cronjobs

Graphs the number of cronjobs active at a certain moment, per user

[plugin/user/cronjobs] Added plugin to monitor cronjobs

---

plugins/mysql/mysql_audit

Shows the number of active connections over time

[plugins/mysql/mysql_audit] Added plugin for monitoring the audit log

---

plugins/network/transmission

Use standard colours for the transmission_activity plot (but keep a
darker one for paused torrents).
Also, remove the ${host} from the graph_title, and add it in the
graph_info, for better groupability.

[plugins/transmission] Fixups for consistency

---

plugins/battery/acpi_batt_
plugins/battery/acpi_sys_batt_

Fix `printf` and `sprintf` output numbers from %s to %d

[plugins/battery] Fix

---

plugins/libvirt/kvm_mem

fix `[WARNING] 1 lines had errors while 66 lines were correct in data from 'config kvm_mem' on <host>`

[plugins/libvirt/kvm_mem] remove empty line from config

---

plugins/docker/docker_

[docker_] Fix a few bugs

---

plugins/loolwsd/loolwsd

Can be used with LibreOffice Online, Collabora Online or Collabora Online Development Edition.

loolwsd: Monitor libreoffice online usage

---

plugins/etherpadlite/etherpadlite_

Multigraph plugin to monitor number of pads in a etherpad-lite instance.

ehterpadlite_: Monitor number of pads

---

plugins/shorewall/shorewall_log

Graphs the number of blocks done by shorewall, given a specific rule suffix

[plugins/shorewall/shorewall_log] Added plugin for monitoring shorewall blocks

---

plugins/network/whois_

[plugins/whois_] stop EXTRACT_RE after the first match

---

plugins/network/transmission

[plugins/transmission] Python3 compat

---

plugins/ssl/certbot_certs
plugins/ssl/certbot_expiry

This plugin will semi-auto discover certbot (letsencrypt) certificates and output their expiry in days.
At this time, it pulls any renewal active certificates.  In the future I may add an option to ignore some, or specify only those you are interested in.

Add "certbot_certs"

---

plugins/nextcloud/nextcloud_

I stupidly forgot to output the `.value` for the data fields in my previous refactor, which completely broke the plugin. Sorry about that...

[plugin/nextcould] Fix incorrect data output

---

plugins/system/file_length_

[file_length_] List full file path in info

---

plugins/http/http_response

- Add "--location" to curl with env.follow_redirect true
- When connections fails, set U (undefined)

http_response: Add follow_redirect and undefined

---

plugins/nextcloud/nextcloud_groupfolders_

Small plugin based on nextcloud_ to monitor in nextcloud specified groupfolders

nextcloud_groupfolders_: Monitor sizes of groupfolders

---

plugins/docker/docker_
plugins/http/http_load_

Fix some AUTHORS so they all show properly in the plugin gallery

---

plugins/ssl/ssl-certificate-expiry

ssl-certificate-expiry: fix handling domains starting with digits

---

plugins/nextcloud/signaling

Plugin for spreed standalone signaling server used for Nextcloud Talk (https://github.com/strukturag/nextcloud-spreed-signaling)

signaling: Plugin for spreed standalone signaling server

---

plugins/disk/raid2

Supports:
- mdstat
- btrfs
- cciss
- megasasctl

raid2: yet another raid+scrub monitoring plugin

---

plugins/debian/debsecan_

For users that desire it, this instanced plugin should have suggest capabilities. I propose suggesting both modes as implemented, as both have their advantages. This will not interfere with existing setups.

Consider adding suggest capabilities to the debian/debsecan_ plugin.

---

plugins/isp/internode_usage
plugins/network/upnpc_
plugins/weather/wunderground_

Loan data from sub-graphs rather than storing it in duplicated series in the root graph of some multigrapdh plugins.

Multigraph root loans

---

plugins/nginx_unit/nginx_unit
plugins/unit/unit

This multigraph plugin does basic monitoring of unit's applications.
See: https://unit.nginx.org/

unit: add new plugin to monitor nginx unit app server

---

plugins/ubiquiti/unifi_api

Putting a fallback value so no error is spammed (Issue #1247)

fix(issue #1247): ubiquiti - unifi_api spamming errors

---

plugins/proxmox/proxmox_vm_count

Hi,
as requested in https://github.com/munin-monitoring/contrib/pull/1250#issuecomment-967193838 i have added the license.

added license to plugin: proxmox_vm_count_plugin

---

plugins/chrony/chrony_status

This graph shows packet rates for the chronyd server.

chrony_status: add a serverstats graph

---

plugins/libvirt/kvm_io

works on debian bullseye with this modification.
removed all codestyle issues, checked with "pycodestyle" on debian bullseye, besides two "line too long"

kvm_io now in python3

---

plugins/libvirt/munin-libvirtpy

works on debian bullseye.
flake8 compatiblity ckecked.
I am not sure with the modified header, just copy&pasted - please feel free to adapt it to be compatible and as wanted - thanks. :-)

munin-libvirtpy now in python3

---

plugins/adguardhome/adguardhome_dns

Display blocking stats, dns queries, client protocols and average
processing time of AdGuardHome

add adguardhome plugin

---

plugins/zfs/zfs_list

Hi,
i have added an option to ignore certain datasets for `zfs_list`.
And updated the Header based on the Old Information within + new Variable.
I think it is useful, because in my case i have many very short lived datasets, that get destroyed and clutter the GUI.
Wishes
mg

added an Ignore Option to zfs_list

---

plugins/proxmox/proxmox_vm_count
plugins/router/mikrotik_system
plugins/zfs/zfs_list
plugins/zfs/zfs_pool_dataset_count
plugins/zfs/zpool_fragmentation

Hi,
i repaired the perldoc headers for my last plugins.
Wishes
mg

Perldoc syntax

---

plugins/quake/qstat

- dash
- bots
- configurable binary

quake/qstat: enhancements

---

plugins/mumble/murmur-stats

- python3 compatibility
- multigraph
- added muted/registered/unregistered users

murmur-stats: Enhancements

---

plugins/network/whois

Also, clean up some old code that pre-dates multi-domain handling

[whois] Allow to specificy whois server per domain

---

plugins/network/dns/dnsresponse_

Like mentioned in https://github.com/munin-monitoring/contrib/issues/1288#issuecomment-1017779708  i have expanded the documentation for dnsresponse_.

Expanded Docs for dnsresponse_

---

plugins/teamspeak/teamspeak_user

- Add environment variables
- Add documentation with good format

[teamspeak_user] Add environement variables and documentation

---

plugins/http/http_responsecode

Related: 282b32b0e54a3bdfb19928f2b87f939fbedcb2bb, e5af569b4f2c006fbdd58939a9578ed2be1502bd

[http/http_responsecode] Add support for host_name

---

plugins/router/snmp__mikrotik
plugins/snmp/snmp__if_combined

Small fixes in a couple of SNMP plugins:
* unify titles and category in snmp__df_ram
* add support for multiple instances of snmp__df_combined

Snmp  fixes

---

plugins/dd-wrt/dd-wrt-wifi-devices_

.. to monitor the number of connected WiFi devices on a DD-WRT based router
http://cweiske.de/tagebuch/dd-wrt-munin.htm

Add dd-wrt-wifi-devices plugin

---

plugins/router/arris-sb8200

This adds a plugin that supports the Arris SB8200 cable modem
- Uptime
- Downstream error counts
- Downstream Signal-to-Noise ratio (dB)
- Downstream & Upstream Power (dBmV)

[arris-sb8200] Add plugin to support Arris SB8200 cable modem

---

plugins/ftp/vsftpd-rel

Use mktemp instead tempfile, as tempfile is deprecated.

Update vsftpd-rel: use mktemp

---

plugins/haproxy/haproxy_rate_frontend
plugins/haproxy/haproxy_sessions_total_frontend

Hi there!
Just a tiny PR to fix ~~a typo~~ _two typos_ in the HAProxy Collector Plugin!

Fix typos in HAProxy Plugin

---

plugins/mail/opensmtpd

This is a new plugin for monitoring the mails sent/bounced/queued/looped for OpenSMTPD https://www.opensmtpd.org/
Supports auto conf

Added opensmtpd plugin

---

plugins/weather/wunderground_

[wunderground_] update default api key

---

plugins/system/hugepages

Also fixes doc typo for /proc path.
Also downcase Anon.label for consistency with other labels.

Support shmem & file hugepages statistics.

---

plugins/deye/deye

This PR adds a new Plugin.
It can be used to monitor Deye Inverters.

add Plugin for Deye Solar Inverters

---

plugins/disk/storagebox_df

This plugin is similar to df plugin, but monitors Storagebox disk instead. It requires config and ssh keys to access Storagebox.

disk/storagebox_df: monitor Hetzner Storagebox disk free

---

plugins/nginx/nginx_vts

This plugin requires https://github.com/vozlt/nginx-module-vts module to be loaded. It provides lot of statistics.

nginx_vts: plugin to monitor nginx statistics with nginx-module-vts

---

plugins/zfs/zfs_list

Set better labels with spaces for zfs_list.

zfs_list: set better labels

---

plugins/git/gitea_commit_time_diff

Add a new Plugin:
``gitea_commit_time_diff``
Plugin to the check the time difference between now and the last commit for a gitea repository.

add new plugin: gitea_commit_time_diff

---

plugins/cicd/drone

add a new Plugin for [drone](https://www.drone.io).

add plugin: drone

---

plugins/cicd/drone

drone: Typo

---

plugins/proxmox/proxmox_vm_count
plugins/router/mikrotik_system
plugins/system/kernel_same_page_merging
plugins/system/zswap
plugins/zfs/zfs_pool_dataset_count
plugins/zfs/zpool_fragmentation

Hi,
this PR fixes the formatting for the Munin Plugin Gallery.
cheers
mg

Fix formatting for Munin Plugin Gallery

---

plugins/onlyoffice/onlyoffice

Plugin that monitors editing and viewing connections of an onlyoffice instance

[onlyoffice] Add plugin for onlyoffice

---

plugins/dhcp/kea

Kea is ISC's recommended DHCP server, old dhcpd is not maintained anymore.
See https://www.isc.org/kea/ for more information.

dhcp/kea: add plugin to monitor Kea DHCP server

---

plugins/gunicorn/gunicorn_memory_status
plugins/gunicorn/gunicorn_status

- Make `gunicorn_memory_status` and `gunicorn_status` Python3 compatible
- Fix PID type (integer)

[gunicorn_*] make gunicorn_memory_status and gunicorn_status python3 compatible

---

plugins/docker/docker_volumesize

This PR adds a Plugin to Monitor the space usage of Docker volumes.

add new plugin: docker_volumesize

---

plugins/nginx/nginx_vts

I forgot to add AUTHOR to my original pull request. Add it.

nginx_vts: add missing AUTHOR tag

---

plugins/systemd/systemd_status

Also add support to ignore specific services.

systemd_status: add support to monitor user services

---

plugins/power/tasmota_

tasmota plugin: implement voltmeter and warning/critical threshold levels

Tasmota voltmeter

---

plugins/network/keepalived

Currently this plugin monitors state of VRRP sync groups and instances. More features, like IPVS, will be added soon.
I will add IPVS and other graphs when I start using them (probably in Jan/Feb). This plugin is written as multigraph plugin for upcoming graphs in mind.

keepalived: plugin to monitor keepalived status and state

---

plugins/sensors/switchbotmeter_multi

Hi,
I would like to add switchbotmeter_multi plugin. It is multi graph version of previous plugin #1236
I would like to add following features.
- support multi graph
- support Switchbot v1.1 API
- support battery graph 
Please consider the pull request.
Thank you!
K.Cima

add switchbotmeter_multi

---

plugins/cpu/process_group

Generic plugin to monitor configured processes. Multiple process groups can be configured with regexps.

process_group: monitor process group age, cpu, memory and count

---

plugins/synapse/synapse_

Shows three graphs of [synapse](https://github.com/element-hq/synapse) matrix homeserver
- event-reports (triggers a warning after 1 event-report)
- users (active, online, deactivated and erased)
- rooms (external, internal, spaces)

[synapse_]: A simple wildcard plugin for synapse matrix homeserver

---

plugins/network/ipsec

This makes it possible to monitor IPsec security associations (up and connecting).

feat: add ipsec plugin

---

plugins/sensors/switchbotmeter_multi

Hi,
I would like to add graph_args --lower-limit --upper-limit to some graphs.
Please consider this pull request.
Thank you!

fix switchbotmeter_multi to add graph_args --lower-limit --upper-limit

---

plugins/sensors/switchbotmeter_multi

Hi,
I would like to improve switchbotmeter_multi plugin as following.
- fix for handling HTTP errors
- fix to fetch data from api in parallel
Please consider this pullreq. 
Thank you!

Fix switchbotmeter_multi

---

plugins/docker/docker_

Requested via mailing list https://sourceforge.net/p/munin/mailman/message/58765217/

Added docker container size plugin

---

plugins/synapse/synapse_

Don't count puppet users (of matrix bridges) as real users.

[synapse_] Ignore puppet users of bridges (last_seen_ts is null)

---

plugins/network/nft_counter

This is a generic plugin for nft counters, although it was requested in https://github.com/FoobarOy/foomuuri/discussions/38.

network/nft_counter: add plugin to graph nftables named counters

---

plugins/security/crowdsec

Add support for [CrowdSec](https://www.crowdsec.net/) using `cscli`

Add CrowdSec plugin

---

plugins/security/crowdsec

Sorry for missing this in the initial commit

Fix spelling mistake in crowdsec plugin

---

plugins/disk/gluster

Gluster is a free and open source scalable network filesystem.
https://www.gluster.org/

disk/gluster: plugin to monitor Gluster volume and brick status

---

plugins/amavis/amavis_

Fix division by zero error on empty cache data. 
Change category to match amavis_multi.

fix division by zero error and change category

---

plugins/power/tasmota_

tasmota can now monitor analog temperature as well as multiple DS18B20 temperature probes.

Tasmota temperature

---

plugins/foomuuri/foomuuri

Add new plugin to graph statistics from Foomuuri. Foomuuri is a multizone bidirectional nftables firewall.
See: https://github.com/FoobarOy/foomuuri
I'm the author of Foomuuri.

foomuuri: plugin to graph Foomuuri statistics

---

plugins/disk/gluster

Healing can be above 0 temporarily, try to handle it better.

gluster: single 0 in healing status means everything is ok, reset avg counter

---

plugins/synapse/synapse_

Re-add forgotten/lost multigraph line which got lost in last commit https://github.com/munin-monitoring/contrib/pull/1472

[synapse_]: Re-add forgotten/lost multigraph line

---

plugins/other/pacman_unrequired_packages

Heavily based on pacman_pending_updates

pacman_unrequired_packages: new plugin

---

plugins/jellyfin/jellyfin_sessions

Add plays and transcodes number

[jellyfin_sessions] Add plays and transcodes numbers

---

plugins/disk/nvme

This is a port of https://github.com/air-gh/munin-nvme-cli/commit/bcce47ad22568fcc87f9e6eab8661dc74486028b with the permission of Air.

add temperature support

---

plugins/languagetool/languagetool_checks

Simple plugin to monitor checks on a self-hosted languagetool server (https://dev.languagetool.org/http-server)

[languagetool] Simple plugin to monitor checks on a languagetool

---

plugins/network/dns/dnsperftest

.. so that I get notified by munin when the DNS server is too slow to respond.
Related: #1439

[dns/dnsperftest] add warning and critical configuration

---

plugins/disk/file_age

.. so the plugin can be grouped into a different host, e.g. backup file timestamps to the "backup" server host.

[disk/file_age] Add support for host_name
