munin-monitoring/contrib

- plugins/unicorn/unicorn_memory_status
- plugins/unicorn/unicorn_status
It would helpful, if the unicorn plugin would display the name of each application monitored, when monitoring several applications.
Instead of reading
* unicorn
* Unicorn - Memory usage
* Unicorn - Memory usage
* Unicorn - Memory usage
I would like to read
* unicorn
* Unicorn [app1] - Memory usage
* Unicorn [app2] - Memory usage
* Unicorn [app3] - Memory usage
for applications configured with the symbolic links
* `/etc/munin/plugins/unicorn_memory_usage_app1`
* `/etc/munin/plugins/unicorn_memory_usage_app2`
* `/etc/munin/plugins/unicorn_memory_usage_app3`
This PR implements the change proposed for both `unicorn_memory_usage` and for `unicorn_status`.
> unicorn: display name of application.

- plugins/mpd/mpdstats_
This patch fixes an error in the example configuration in the plugin doc.
The plugin-conf.d/munin-node section had a wrong name.
> mpdstats_: fix example documentation.

- plugins/gpu/nvidia_gpu_
The "Avoid bashism" commit does not work with /bin/bash (including RedHat, etc where /bin/sh is symlinked to /bin/bash). A subsequent commit to fix the shebang to /bin/bash solved the issue (for Debian/Ubuntu at least, theoretically everywhere).
> Revert "Avoid bashism"

- plugins/nginx/nginx_error
Reading the log-file status counters ONCE into an array instead of reading the log-file over and over again for each status code. Especially helpful when having huge log-files. In my case it dropped the exec-time by around 80%.
> Enhance nginx_error plugin

- plugins/snmp/snmp__ups_
Changes:
- More queries supported (inputpower, batterycurrent, batteryruntime (how long
have we been running on battery), batterypercent (percent remaining),
inputlinebads (how often was input bad))
- fix a few wrong units (e.g. current is measured in amp, not in watt)
- some UPSes violate RFC 1628 by not returning the number of input-/
output-lines they have. In this case assume 3 lines instead of 0
(and just printing nothing at all).
- Make mode parameters all lowercase instead of camelcase - camelcase
just looks retarded in the plugin-symlink-names.
- some more smaller fixes
> overhaul of snmp__ups_ plugin.

- plugins/firebird/firebird
* Use gstat from path if available; fall back to /opt/firebird/bin/gstat if gstat could not be found
* Use bash to strip of firebird_ prefix from name
* Fixed description
> Fixed firebird plugin:

- plugins/network/avm-fritzbox-wan-traffic
With the latest firmware update to 6.20 on the fritzbox 7390, the data fetching was broken. The url with the data could not be found anymore.
This corrects the url.
> modified data_url for firmware >= 6.20

- plugins/varnish4/README.md
- plugins/varnish4/varnish4_
The hit rate caluclation is correct as long as no purges are performed. If purges are performed, they are counted in client_req, but not counted in cache_(hit|miss|hitpass). This would lead to wrong values for the hit rate because client_req is bigger than the sum of cache_(hit|miss|hitpass).
Additionally there are some minor bugfixes.
> Fix hit rate calculation for varnish4 plugin

- plugins/network/mtr100_
Newer versions of mtr outputs a "Start: <date here>" line which would be
picked up and incorrectly graphed in munin. Adding an additional inverse grep
field to remove this extra line if it is present. Also added case insensitive
flag to the grep.
Old output of mtr100_*:
```bash
~  mtr -nrs 1024 -c 5 8.8.8.8 | grep -v "^HOST:"
Start: Tue Dec 23 18:37:19 2014
1.|-- 192.168.1.1                0.0%     5    0.4   0.4   0.4   0.5   0.0
2.|-- 10.125.122.129             0.0%     5    8.7   9.0   8.7   9.3   0.0
3.|-- 69.63.242.49               0.0%     5   12.4  14.6  12.4  21.7   4.0
4.|-- 64.71.241.97               0.0%     5   15.1  15.4  13.6  17.8   1.5
5.|-- 69.196.136.68              0.0%     5   17.2  15.6  11.6  24.0   5.1
6.|-- 72.14.212.134              0.0%     5   12.5  15.8  11.9 …
```
> Removing erroneous line from mtr output.

- plugins/redis/redis_
This allows setup of multiple redis instances on a single server instance and allows the graphs to be distinguishable.
Currently if you setup multiple by using instance1_redis_connections and instance2_redis_connections both set of graphs have the same name.
> Add TITLE_PREFIX to redis_

- plugins/sensors/allnet__
new plugin to feed sensor information from Allnet IP sensoric devices like e.g. ALL4500 into munin. It uses the XML-Interface of the devices to fetch data.
Example graph:
> new plugin for monitoring allnet ip sensoric devices (e.g. ALL4500)

- plugins/zfs/zfs-filesystem-graph
Providing a --upper-limit parameter is only useful if the size of the
filesystem never changes. On ZFS, this assumption is only true for the
zpool; for all other filesystems, the available space is shared, and the
totalled values will vary. When this is the case, the --upper-limit
parameter will obscure peaks in the graph.
> zfs-filesystem-graph: remove --upper-limit

- plugins/disk/raid-mismatch-count
* redirect error message of `ls` to /dev/null
* ```ls: cannot access /sys/devices/virtual/block/*/md/mismatch_cnt: No such file or directory```
* fetch mismatch_cnt to get correct count
* https://www.kernel.org/doc/Documentation/md.txt
* sync_completed: the number of sectors that have been completed
* mismatch_cnt: the number of errors that are found
> fix - remove error message, fetch correct count source

- plugins/disk/raid
* refactoring/change
* replace TAB with 8 spaces
* use lexical variable for file handle
* split a single regex matching to three matchings
* value of array, rebuild and check should be 100 while array is idle.
* fix
* mdadm has '--readonly' option to make the array 'active (read-only)'
* enhancement
* use only /proc/mdstat, stop forking /sbin/mdadm
* fetch remaining time of array rebuilding and show them on config
> refactoring, bugfix and enhancement for disk/raid plugin

- plugins/php/php_apc_
Make capitalization and grammar consistent (e.g. Missed -> Misses)
> Make capitalization and grammar consistent

- plugins/postfix/postfix_mail_stats
Original script was broken and reported all emails as sent.
Also, `grep | wc -l` is pure evil.
> Fixed sent/received count and replaced wc -l with -c

- plugins/zfs/zfsonlinux_stats_
I wanted to get all these ZFS stats on my ZFSonLinux install, so I modified the FreeBSD plugin to read from the stats files generated by the SPL module instead. I also added some checks to make sure I wasn't dividing by zero in a number of places. From an output perspective, this produces the same values as the zfs_stats plugin.
> Added zfsonlinux_stats plugin

- plugins/rabbitmq/rabbitmq_queue_memory
```
Error output from rabbitmq_queue_memory:
erlexec: HOME must be set
```
> Fixed typo in rabbitmq_queue_memory

- plugins/zfs/zfsonlinux_stats_
Re-submitting the zfsonlinux_stats_ plugin as it got butchered by my shoddy commits when merged. This looks like a duplicate of #562 but that merge was actually undone by #563. I'm still bad at git, years in.
I'll include the original description here for clarity:
I wanted to get all these ZFS stats on my ZFSonLinux install, so I modified the FreeBSD plugin to read from the stats files generated by the SPL module instead. I also added some checks to make sure I wasn't dividing by zero in a number of places. From an output perspective, this produces the same values as the zfs_stats plugin.
Thanks!
> Re-submit zfsonlinux_stats_

- plugins/virtualization/kvm_cpu
- plugins/virtualization/kvm_io
- plugins/virtualization/kvm_mem
- plugins/virtualization/kvm_net
fixed regex for "vm_name" resolving, so VMs with dash (e.g. "db-test") in the name will be displayed correctly.
> fixed kvm_* plugins

- plugins/cyrus/cyrus-imapd
First, try to look for proc_path: config parameter.
If it doesn't exist, fallback to old method, and extrapolate the configdirectory: config parameter
> cyrus-imapd:

- plugins/postgresql/postgres_space_
If the user as whom "munin" connects has no rights to list existing DBs,
the plugin crashes. Even though the rest of the code is OK. Listing DBs
is only necessary in the case of auto-configuring the plugin. Not for
running it.
This removes the line which causes the bug. The variable which is set in
this line is anyway not used.
> Plugin runs, even if no access to list DBs.

- plugins/snmp/snmp__synology_hddtemp
- plugins/snmp/snmp__synology_temperature
- plugins/snmp/snmp__synology_ups
Synology specific snmp plugins for:
- System temperature
- HDD temperature
- UPS Charge & Load
I noticed there is already a multigraph plugin for temperatures, but sadly the other one is using python with pysnmp which may not be installed on every system.
> Add snmp__synology_* plugins

- plugins/ups/apc_status
Added mutigraph capabilities and automatic unit detection.
Fixed regex:
`egrep "$key"` was returning multiple matches when using "BATTV" as key.
Fixed by using `egrep "^$key"`.
This prevents the key `NOMBATTV` from being matched by the string `BATTV` while still allowing it to be matched by `NOMBATTV`
> [apc_status] Added multigraph capabilities and fixed regex

- plugins/postfix/postfix_mailqueue_
It is very hard to see the real values in the postfix queue when they
are overlapping. Having a stacked graph eleviates this whil still
retaining all the necessary data.
> Stack postfix mailqueues instead of overlapping.

- plugins/memcached_ext/memcached_ext_bytes_
- plugins/memcached_ext/memcached_ext_connections_
- plugins/memcached_ext/memcached_ext_hits_
- plugins/memcached_ext/memcached_ext_items_
- plugins/memcached_ext/memcached_ext_requests_
- plugins/memcached_ext/memcached_ext_traffic_
- plugins/redis/redis_
rewrite memcached family plugins: bytes_, connections_, hits_, items_, requests_, traffic_
for unix socket usage
> rewrite memcached family plugins for unix socket usage

- plugins/moodle/moodle_files.php
currently graph_scale is not functionnal in moodle file size graph due to an insconsistency between 2 value of graph_scale. This PR fix it :)
> file_size graph : useless graph_scale removal

- plugins/openntpd/openntp_offset
Add a plugin that, like ntp_offset plugin, measures offset, delay and jitter
for the active OpenNTPd peer.
> Add openntp_offset plugin.

- plugins/monit/monit_parser
When a daemon fails `-nan` is its memory usage.
> [monit] Not using memory is a warning condition

- plugins/mail/policyd-spf-python
Very simple but useful plugin to monitor postfix-policyd-spf classification results. Written by me some time ago, but still works :)
> add postfix-policyd-spf-python plugin

- plugins/jenkins/jenkins_
Some build statuses reported by Jenkins were not counted by this plugin, since counting was done using the unmapped versions of the status names. This PR fixes that, with some related (though trivial) improvements along the way.
> Jenkins fixes

- plugins/weather/openweather_
OpenWeather needs you to use an API key since Oct 9 2015. Therefore I added env.apikey.
To get a key just register at OpenWeather.
> p: openweather_: Add OpenWeather API Key

- .travis.yml
- t/test.t
Currently plugins fail to compile if they use Python 3 syntax features,
even though they use a correct shebang.
> tests: test compiling with python3 if given as shebang interpreter

- plugins/streaming/icecast2_stats_
This icecast plugin captures a set of data similar to the "icecast2_"
and "icecast2_all" plugin. Sadly both are not configurable (manual
changes are required for target host and access credentials).
Additionally they use the rather old-fashioned (and password restricted)
xml status output.
This new plugin "icecast2_stats" (written from scratch) contains the
following notable differences:
* runs with Python 3
* supports a real "autoconf" and "suggest" interface
* is configurable (target host and port) via environment settings
* uses the json status output instead of the xml data
* contains no hard-coded values, names or patterns
> streaming: add configurable icecast2 plugin

- plugins/virtualization/kvm_cpu
- plugins/virtualization/kvm_io
- plugins/virtualization/kvm_mem
- plugins/virtualization/kvm_net
Debian Jessie processes name are ```qemu-system-x86_64``` not ```kvm```.
Maybe the plugin should detect  ```qemu-system-x86_64``` or ```kvm``` and chose the right one.
So here is a patch for Debian Jessie (only? Maybe recent KVM?).
> Support for Debian Jessie.

- plugins/varnish4/README.md
- plugins/varnish4/varnish4_
Updated README.md with the config changes needed for 4.1
Updated varnish4_ so it is displays graphs that were not generated in 4.1 because the type was unknown to munin. 
This will resolve issue #660
> Varnish 4.1 update

- plugins/backuppc/backuppc
should help to find the long-time-without-backup systems.
> backuppc: add CRITICAL and WARNING (backup age) variables.

- plugins/gunicorn/gunicorn_memory_status
- plugins/gunicorn/gunicorn_status
Add instance name to the graph titles for the gunicorn_status and gunicorn_memory_status plugins when linked as gunicorn_INSTANCE_PLUGIN or gunicorn_PLUGIN_INSTANCE.
> Instance name in graph title for gunicorn plugins

- plugins/varnish4/varnish4_
As usual for percentage based graphs (cpu, df etc).
Otherwise it might autoscale and look weird.
> varnish4: lower limit 0 in hit rate graph args

- plugins/apache/apache_cache_disk_count
Absence of associative arrays/object in munin configuration makes (flexible) configuration a bit more complex that it should.
> apache_cache_disk_count plugin

- plugins/network/if1sec_
* look for already running acquire process, or start one
* use CDEF to return bits/second (like if_)
* increase lifetime to 450 days (like if_)
* changed category to plain "network" (like if_)
* report max interface speed (like if_)
* small performance improvement: don't fork two cat(1) and one date(1) every second (this roughly halves the CPU time used on my system)
> if1sec_: implement autostart, be more like if_

- plugins/lxd/lxd_disk
- plugins/lxd/lxd_mem
lxd is the abstraction of lxc containers and provides multiple additional services. Through a REST interface and pylxd it provides a lot of metrics about running containers which can be graphed. To run it, the munin user must either be in the lxd group or the plugin must run as root in the `munin-node` config
[lxd_*]
user root
Creating a new plugin for another value, such as network traffic, can easily be copied from these ones.
> lxd plugins

- plugins/network/dhcp-pool
This pull request fixes two minor bugs in the `dhcp-pool` plugin. When parsing the `dhcpd.conf` file: Commented-out lines containing the `range` statement were not ignored (same as #745). Number of addresses included in each `range` was calculated incorrectly.
> dhcp-pool: fix conffile parsing

- plugins/network/zenus_
* Plugin will now not forecast allowance usage on unlimited accounts.
* Plugin also "backs off" data collection when querying fails (this is Zen's recommended response to errors)
> zenus_: Handle "unlimited" accounts

- plugins/znc/znc_logs.py
znc_logs now handles:
* Post 1.6-style log paths
* User as well as Channel plots (maybe this should go multigraph?)
* Letting Munin/RRD calculate the log rate (by setting the type to ABSOLUTE and only saying how many lines have been read in the last 5 minutes)
* Remembering what channels were seen (optional)
> znc_logs.py: Rework to tail_open log files

- plugins/network/ath9k_
add network plugin:"ath9k"
Collect information related to ath9k wireless events and states:
* rate control statistics ("rc_stats")
* events (dropped, transmitted, beacon loss, ...)
* traffic (packets, bytes)
All data is collected for each separate station (in case of multiple connected peers).
Combined graphs are provided as a summary.
> network: wireless ath9k

- plugins/network/wireless_channel_occupation_
This plugin tracks the occupation of the shared medium (wifi channel).
It uses the "iw" tool for extracting the time slices spent by
the wireless driver receiving, transmitting or ignoring (noise) on the
current channel. This ratio is a good indication for the remaining
capacity of the shared communication medium.
> new network plugin added: wireless_channel_occupation

- plugins/mongodb/mongo_lock
The `globalLock.totalTime` and `globalLock.lockTime` have `$numberLong` field on MongoDB 2.6:
```
globalLock: {
totalTime: {
$numberLong: "2858903123000"
},
lockTime: {
$numberLong: "144783780"
},
...
```
It needs to read `$numberLong` field.
> Fix bug where can't read MongoDB lock ratio

- plugins/dovecot/dovecot
If dovecot plugin found dovecot-only log it will analyse it without filtering by 'dovecot' tag
> 689-dovecot-plugin-log-file-format

- plugins/time/ntp_packets
Works on python 2.7.10 now.
I'm not aware of a single distro which doesn't have python2.x available, however the reverse case is not true:
Some systems have python3.x blacklisted, but since there's nothing about this plugin so complicated it can't work on the more widely deployed python 2.x it took less than 10 minutes to backport.
> python3 dependency fixed (backport)

- plugins/backuppc/backuppc
With this change there are two separate graphs:
* one for the age of the last backup (either incr/full)
* one for the age of the last full backup
If you update your backuppc plugin to the new version, the lines showing the last full backup age will be removed from the "last backup" graph, the new "last full backup" graph will be empty and start a-new.
> backuppc: Split age graph into last backup / last full backup

- .travis.yml
- plugins/network/vnstat_month
This broke in an update to Debian Jessie.
> vnstat_month: suppress warnings in perl 5.18+

- plugins/postgresql/pgbouncer_
Our use case needs to have two different pgbouncer_ plugin instances (for two pgbouncers listening on different ports), while these pgbouncers are connecting to same database. Since database ("pool") name is taken from plugin suffix, it was not possible to implement in current version.
This patch allows to specify pool name explicitly in config file, so now plugin name does not have to match database name. If pool name is not specified in config file, _old plugin behavior persists_.
> pgbouncer_: allow to separate plugin name and pool name

- plugins/ssl/ssl_
This allows to specify and optional port to the `ssl_` plugin, by adding `_PORT` to the symlink. If unspecified, this defaults to 443 as before.
> Ssl non https

- plugins/network/wifi_signal_noise_
This new plugin offers the following advantages compared to the existing wifi_signal plugin:
* support multiple wifi peers (e.g. mesh mode or master mode with multiple clients)
* use "iwinfo" or "iw" for information retrieval (instead of Linux's procfs)
> network: new wifi_signal_noise_ plugin for signal strength and noise

- plugins/virtualization/vserver/vserver_jiffies
- t/test.t
* Switch to zsh (used to be bash)
* Fix to remove dots from vserver names (replace them with underscores; dots confuse munin)
* Drop support for old (pre 2.6.19) kernels
* Replace cat | grep | cut pipelines with a single sed each
* Add env.stripdomain (a domain name to strip from the end of vserver names when generating labels; be sure to include the leading dot)
> plugins/virtualization/vserver/vserver_jiffies: several enhancements (but zsh)

- plugins/mysql/mysql_connections_per_user
This is the user name used internally by mysql for binlog handling (even
though it's not present in the mysql.user table).
The space in the name makes the plugin freak out about an unknown
"system" value.
Number of connections for this interal user is irrelevant.
> mysql_connections_per_user: skip internal user "system user"

- plugins/time/ntp_packets
Reverts munin-monitoring/contrib#701
Changing the code to Python 2 is an unacceptable regression. The © symbol is not a problem.
> Revert "python3 dependency fixed (backport)"

- plugins/oracle/oracle_sysstat_
I updated oracle_sysstat_ plugin. I have tested it in a few days and it looks working fine. Please consider this pullreq.
* Add modules
logon
cputime
blockrw
redosize
eventwaitnetwork
eventwaitadministrative
eventwaitconfiguration
* Update modules
cachehit: Changed to calculate hit ratio between munin-node update intervals by CDEF
sessionwait: Add CPU status, Add graph_info
table_fetch: Add table_fetch_continued_row field
pgastat: Add aggregate PGA target parameter field
* Improvement
Change not to execute sqlplus in for loop in getvalue funcs to improve performance
Change to add field.min 0 when type is DERIVE
Add label_max_length in config() to suppress new line in graph image
Change graph_title for sorting
* Fix styles
Enable set -o nounset
Add double quote to suppress shellcheck …
> Update oracle_sysstat_ plugin

- plugins/php/php_opcache.php
as per http://php.net/opcache_get_status passing false to `opcache_get_status()` will reduce unnecessary generation of per scripts stats data.
> dont waste time by retrieving per script stats

- plugins/http/http_load_
Munin 1.0 supports fieldnames of at most 19 characters. For domain names
longer than that, this plugin simply truncate the names in its own cache
down to 19.
This creates an issue with the `response` graph, which appends the HTTP
status code to the hostname to make multiple variables. Truncating to
this string loses this information, leading to an empty graph.
> Http load  fix long domains

- plugins/weather/openweather_
Use expr to extract values and names from the OpenWeather API xml instead of the, when having a city with spaces in its name not correctly working fgrep | tr | cut construct.
> p: fixing openweather_: replaced fgrep, tr, cut with expr

- plugins/other/wordpress-multisite
A Munin plugin to monitor posts, comments and pingbacks from every multisite instance.
It uses multigraphs and also shows the combined number of posts, comments, pingbacks, instances and users.
Most database requests came from the wordpress-mu-plugin which was written by Andre Darafarin and Chris Bair
> wordpress-multisite

- plugins/other/wordpress-multisite
The variable NETWORK_SIZE was filled by network_size if declared. But documentation said that the other variable was called networksize. Changed it to the latter.
(Hope this is the right place after the old pull request was done?)
> wordpress-multisite: wrong variable name

- plugins/monit/monit_parser
Add optional preemptive HTTP Basic Authentication to HTTP request in order to support monit configuration like "set httpd port 2812 allow munin:s3cr3t read-only"
> monit_parser: Support Authentication

- plugins/snmp/snmp__juniper
The current recommended firmware for EX3400 (JUNOS 15.1X53-D55.5) lists the routing engines as 'Routing engine <member id>' when the switches are stacked in a Virtual Chassis.
The former code failed to detect these strings, so I relaxed it a bit.
This matches the documentation found here: https://kb.juniper.net/InfoCenter/index?page=content&id=KB17526&actp=search
> Correctly detect the Routing Engines on Virtual Chassis

- plugins/disk/dirsizes
This PR changes value name computation by only keeping alphanumeric characters, hyphens and underscores. The previous list (`/\-`) was not enough to ensure value names were valid.
> dirsizes: fix directory labels

- plugins/disk/disk-io-multigraph-munin-plugin
- plugins/http/http_load_
- plugins/http/http_request_time
- plugins/mail/postfix_mail_stats
- plugins/memcached/memcached_multi_
- plugins/minecraft/minecraft-users-ram_
- plugins/modem/cisco-epc3010_
- plugins/network/dns/dnsresponse_
- plugins/nginx/nginx_byprojects/byprojects_access
- plugins/nginx/nginx_byprojects/byprojects_bandwidth
- plugins/nginx/nginx_byprojects/byprojects_inout_bandwidth
Review of "other" plugins. If the gallery build script doesn't find pure string graph_category some-category the plugin will be put into default category "other". With this commit, I fixed some of these.
Btw. We have to think about multi-plugins. The build script is at the time not able to handle multiple categories..
In this commit I made changes on one multi-plugin that defined sort of sub-categories referring all to "memcached". Therefore I set them all to their /top-category/ to reduce the number of categories we present per default in the Munin tree. If a user want's to have more or other categories shown in her/his Munin instance: set your own categories for the plugins in Munin-Master configuration (Node-Tree of munin.conf)
> Category Tree: Reduce number of categories

- plugins/nginx/nginx_error
If the only file found is empty (access.log with the default pattern), the following error happens:
```
/etc/munin/plugins/nginx_error: line 104: line_counts[${tmp[1]}]: bad array subscript
```
This patch will prevent the crash by testing if any values were found.
> fix crash if access.log is empty

- plugins/varnish/varnish4_
Varnish4_ plugin displays categories in an arbitrary order, changing
the colors of the graphs with each run.
This fix introduces a 'sort' statement in the category iteration function
to force the same order consistently.
Fixes issue #819
> Fix inconsistent category order of varnish4_ plugin

- plugins/solaris/forks
- plugins/solaris/fsstat_act_
- plugins/solaris/fsstat_bytes
- plugins/solaris/interrupts
Hello,
I would like to add some plugins for Solaris OS, that look lacking in comparison with Linux OS. Please consider thus pull request.
- interrupts: plugin to monitor cpu interrupts, context switches and related events. It can be equivalent of Linux interrupts plugin. 
- forks: Plugin to monitor fork and exec rate. It can be equivalent of Linux forks plugin.
- fsstat_bytes: Plugin to monitor file system statistics. 
- fsstat_act_: Plugin to monitor detail activities of file system statistics.
> Add interrupts, forks, fsstat_bytes, fsstat_act_ plugins for Solaris

- plugins/ssh/openssh-denyhosts
`/var/lib/munin/plugin-state` even doesn't exist on Ubuntu 16.04
> Use $MUNIN_PLUGSTATE instead of hardcoded path

- plugins/openwrt/snmp__memory_openwrt
Basically a rewrite of the existing plugin:
- Added documentation
- Updated to use Munin::Plugin::SNMP
- Fixed OID for snmpd on latest builds of OpenWrt/LEDE
> Fix OpenWrt SNMP memory plugin

- plugins/postgresql/postgresql_transactions
The current output of this script is:
```
root@master:/etc/munin/plugins# ./pg_transactions 
\ncommits.value xxxx\nrollbacks.value xxxx
```
By removing the first `\n` and by adding an `E` before the second `\n` the output is:
```
root@master:/etc/munin/plugins# ./pg_transactions 
commits.value xxxx +
rollbacks.value xxxx
```
And lastly by adding the `--no-align` attribute you get the correct output:
```
root@master:/etc/munin/plugins# ./pg_transactions 
commits.value xxxx
rollbacks.value xxxx
```
> Fixed output of transactions script

- plugins/zfs/zpool_capacity
I made zpool_capacity plugin. It monitors ZFS storage pool capacity. I have tested this plugin with Solaris 10 and 11, OpenIndiana Hipster, FreeBSD 11, CentOS 7.
> Add zpool_capacity plugin

- plugins/pdns/pdns_errors
- plugins/pdns/pdns_latency
- plugins/pdns/pdns_qsize
- plugins/pdns/pdns_queries
- plugins/pdns/pdns_rec_answers
- plugins/pdns/pdns_rec_cache
- plugins/pdns/pdns_rec_cache_size
- plugins/pdns/pdns_rec_concurrent
- plugins/pdns/pdns_rec_issues
- plugins/pdns/pdns_rec_outqueries
- plugins/pdns/pdns_rec_qtypes
- plugins/pdns/pdns_rec_querylatency
- plugins/pdns/pdns_rec_questions
- plugins/pdns/pdns_rec_throttle
- plugins/pdns/pdns_rec_unauth
- plugins/pdns/pdns_rel
The init script is not usable on systems using systemd (e.g. Debian stretch).
autoconf is also made conditional on the existence of the executable to not enable the plugin on systems where pdns is not installed.
> Use pdns_control utility instead of pdns init script.

- plugins/other/pacman_pending_updates
As the title says, this update adds information about which updates are pending to the extinfo field. This makes warnings much more informational, since it tells you whether you really need to update now or if you can wait for a while.
> Add specific updates to extinfo field.

- plugins/mail/nullmailer_queue
This PR adds a plugin for monitoring the queue size for the nullmailer MTA. Nullmailer is a simple MTA that can only work with an SMTP smarthost rather than serve mail itself.
The plugin monitors queue size and the size of the "failed" folder. Folder locations are configurable from the environment.
> Implement plugin for monitoring nullmailer.

- plugins/disk/raid
This addition is very useful for me, especially with spare disks which can be rebuilt when nobody is watching so you would miss failed disk if you didn't notice rebuild.
> count failed disks and report critical warning

- plugins/zfs/zfs_usage_
The current code escapes / (which is legal as part of a dataset name for ZFS, but illegal as part of a munin graph name) into _ (which is legal for both). The result is that any _ characters in the original filename get changed into / in the legend, which is confusing.
Fix by escaping any existing _ characters into __ first, and then later replacing // into _ again. // is a sequence that will not occur in a ZFS dataset name, so any double-/ sequence must therefore have been a _ originally.
> Allow for _ in original dataset name

- plugins/README.md
Missing protocol caused it to link to a nonexistent place on github.
> Fix broken link in plugin README

- plugins/disk/du-2
Update du-2 to fix "No .label provided" error by using clean_fieldname().
Before:
After:
> Fix du-2 to use clean_fieldname()

- plugins/ssh/sshd_log
Now shows the number of events per time unit, instead of a counter
always increasing until logrotate.
To use journald, set env.logfile to special value 'journald': It will
read the sshd logs from journalctl _COMM=sshd.
To configure the source of journald, set env.journalctlarg:
Example: "env.journalctlarg --unit=sshd.service"
Previous discussion: #770.
This version uses journald cursor to only parse new logs on each run.
> other/sshd_log: use DERIVE datatype and support logs from journald too (using cursors)

- plugins/zfs/zpool_iostat
As default installation of FreeBSD does not include gawk, change the dependency from gawk to awk will be nice for some platforms other than Linux.
> change dependency from gawk to awk

- plugins/disk/linux_diskstat_
Reading from /sys/block/*/stat does not provide the disk major and minor
numbers (versus reading from /proc/diskstats). When saving the disk data
back to a temp state file, these empty values for the disk major and
minor numbers get turned into undef values on state restore.
On the line: `my ( $prev_time, %prev_diskstat ) = restore_state();`
`%prev_diskstat` will 'slurp' up all returned values from the function
call (converting the list into key value pairs) but if one of last
values is from the major or minor number (which will be undef), the key
(major or minor) will be sent but the undef value will not be
sent. Hence this results in an attempted hash assignment where one of
the key values pairs is missing a value and thus the 'Odd number of
elements in hash assignment ' warning is …
> Fix Odd number of elements in hash at linux_diskstat_ line 321

- plugins/postfix/postfix-rbl-blocked-mails
* style cleanup
* reduce code duplication
* use only top-level-domains of RBL providers for identification
See #928
> Plugin postfix-rbl-blocked-mails: various improvements

- plugins/ceph/ceph_osd
* 'ceph -s' text output format strongly depends upon ceph version. Using JSON format to obtain data works across different ceph versions.
* Execute 'ceph -s' only once to get data
>  Use JSON format to obtain data from 'ceph -s' 

- plugins/disk/du-2
Don't exit with error if cache file is missing, instead refrain from sending values and daemonize() in an attempt to generate one.
Invocation using 'config' before generation is successful will fail, as mentioned in #914, but configuration will get picked up as soon as it is present.
> Generate cache file if missing

- plugins/nginx/nginx_error
@sumpfralle in the commit https://github.com/munin-monitoring/contrib/commit/0e864944d76b19278d82a602aca850c0d91ac51a forgot the fix merged in https://github.com/munin-monitoring/contrib/pull/813 
The log files may be empty, and without this fix this error occurs:
```
Error output from nginx_error_phpMyAdmin:
/etc/munin/plugins/nginx_error_phpMyAdmin: line 126: line_counts[$status_code]: bad array subscript
```
> Nginx error: log files may be empty

- plugins/systemd/systemd_units
Updated to allow admin to set custom values for warning and critical levels for all `$state` fields.
> Added print_{warning,critical} for greater flexibility

- plugins/systemd/systemd_units
I'm running Ubuntu 16.04, which has a version of `systemd` that has a bug preventing failures to show as `failed` for units that use the `Restart` clause. Thus, to get the information (and alerts) that I need from the system, I had to implement filtering so I could monitor just the unit files I cared about and then create alerts for failed _and inactive_ units.
These updates add both global and state-specific unit filtering to facilitate that.
> Added detailed filtering capabilities for systemd_units

- plugins/systemd/timesync_status
This patch adds a plugin that monitors the usual NTP stats for `systemd-timesyncd`. It can do autoconf and requires no configuration on regular systems.
It depends only on a reasonably modern version of Python (3.5+) which has been shipped in the latest (and sometimes previous) LTS releases of most popular distros, save for CentOS.
> Create plugin timesync_status to monitor systemd ntp.

- plugins/mail/nullmailer_queue
This commit enables thresholds to be set for the total size of the nullmailer queue.
It uses the print_warning and print_critical functions from plugin.sh, so configuration should be pretty standard.
> Add support for configurable thresholds to nullmailer_queue plugin

- plugins/jvm/jstat__gccount
- plugins/jvm/jstat__gctime
- plugins/jvm/jstat__heap
jstat column output is not stable across JVM versions (technically
version of jstat binary used).
New columns are added not add the end of column list but in the middle
breaking access via constant index.
Following table shows the known columns per version:
Oracle JDK / OpenJDK 1.5 .. 1.7
S0C    S1C    S0U    S1U      EC       EU        OC         OU       PC     PU    YGC    YGCT   FGC     FGCT    GCT
Openjdk 1.8 .. 10
S0C    S1C    S0U    S1U      EC       EU        OC         OU       MC     MU    CCSC   CCSU   YGC     YGCT    FGC    FGCT     GCT
Openjdk 11  .. 12
S0C    S1C    S0U    S1U      EC       EU        OC         OU       MC     MU    CCSC   CCSU   YGC     YGCT    FGC    FGCT     CGC    CGCT     GCT
Earlier commit here added support for java8+ but using version checking
if …
> Fix jstat* plugins to work again with java 6+7, fix PU reporting for Java8

- plugins/jvm/jstat__heap
Fix regression in last commit. While it added auto-detection of changing
column position it did not take into account the known change from
Java 7 > 8.
Java <8 had the Permanent Generation region which jstat columns PU, PC
While Java >=8 now has a Metaspace region (for similar purpose) with
jstat columns MU,MC.
Add re-add detection for that change to fix reporting of the values.
To simplify code uses the MU,MC labels internally and when MU,MC are
not found in jstat output it fills those with PU,PC values.
Note:
- Not really supper happy with needing to add that if but i did not find a really clean solution
- Detection now based on MU column present in jstat output instead of java>8
Tested now with running jvm + jstat binary both from same jvm with
- jvm oracle 1.5 and openjdk 1.7  (both …
> Fix reporting of 'Permanent Generation' / Metaspace (for java<8)

- plugins/disk/dirsizes
Directory names were not being quotes for du.
Also added automatic globbing of directories to enable stuff like /home/*
> Fix spaces in directory names. Glob directories.

- plugins/ubiquiti/unifi_api
new controllers require the use of double quoted string to login, thanks to @fongd for catching this.
> Ubiquity Plugin: login error fix

- plugins/systemd/systemd_units
Running it with sh results in this error:
```
/etc/munin/plugins/systemd_units: 109: /etc/munin/plugins/systemd_units: Bad substitution
```
> Change shebang of systemd/systemd_units from sh to bash

- plugins/xen/xen-multi
There is a bug in xentop, its output is too high in rare cases.
https://lists.xenproject.org/archives/html/xen-users/2019-04/msg00020.html
Workaround to process 3 iterations after the first one (4 itrations) and choose the lowest cpusecs value line.
> Plugin xen-multi: xentop bug workaround

- plugins/tor/tor_
1. Fixes
```
munin-run tor_bandwidth 
File "/etc/munin/plugins/tor_bandwidth", line 448
onr = 0
^
TabError: inconsistent use of tabs and spaces in indentation
```
2. Use single quotes consistently also for GeoIP.dat filename
> Fix "TabError: inconsistent use of tabs and spaces in indentation"

- plugins/postfix/postfix-rbl-blocked-mails
With this commit it's now possible to add custom Realtime Blackhole Lists via a env.rbls
> Plugin postfix-rbl-blocked-mails: adds custom RBLs monitoring

- plugins/tor/tor_
Setting
`env.torconnectmethod 'port'`
leads to the error:
```
munin-run tor_bandwidth 
env.torconnectmethod contains an invalid value. Please specify either 'port' or 'socket'.
```
Removing the quotes solves that, because the quotes are part of the variable value.
["There is no need to quote the variable content."](http://guide.munin-monitoring.org/en/stable-2.0/plugin/use.html)
> Remove quotes in plugin env parameters

- plugins/other/pacman_pending_updates
Previously, when retrieving update counts failed, the plugin reported no updates. This is incorrect. With this patch, the plugin should properly report UNKNOWN.
No additional error handling is needed, since `checkupdates` reports a clear error message when it fails.
> Exit when retrieving updates fails.

- plugins/system/file_length_
* Only show extinfo if stat is the GNU version
* Unify variable references
* Better legend when type is not GAUGE
> [file_lenght_] Various fixes

- plugins/libvirt/kvm_cpu
- plugins/libvirt/kvm_io
- plugins/libvirt/kvm_mem
On Debian Stretch the cmdline is something like:
`qemu-system-x86_64-enable-kvm-nameguest=vmname,debug-threads=on-S-[…]`
Without null characters:
`qemu-system-x86_64 -enable-kvm -name guest=vmname,debug-threads=on[…]`
We need to match only `guest=vmname`, so the regex
`^.*guest=([a-zA-Z0-9.-_-]*).*$` is simpler and match the VM name.
The previous regex `^.*-name\x00([a-zA-Z0-9.-_-]*)\x00\-.*$` was not matching it.
BTW, It seems that `\x00` does not match correctly null characters so I removed it.
> libvirt/kvm_*: Simpler regex to match VM name

- plugins/bsd/uptime_bsd
compile time is not included since FreeBSD 12.0-RELEESE due to Reproducible Builds.
https://wiki.freebsd.org/ReproducibleBuilds/Base
https://reviews.freebsd.org/D4347
sysctl output samples:
% (11.2-RELEASE) sysctl kern.version
kern.version: FreeBSD 11.2-RELEASE-p10 #0: Mon May 13 21:20:50 UTC 2019
root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC
% (12.0-RELEASE) sysctl kern.version
kern.version: FreeBSD 12.0-RELEASE-p7 GENERIC
> fix uptime_bsd. compile time is not included since FreeBSD 12.0

- plugins/chrony/chrony_drift
Information concerning how to use variable env.driftfile is wrong. Specifying these variable as is in plugin-conf.d/00-defaults not work if double quote is used.
> Remove double quote for env.driftfile variable

- plugins/mysql/mysql_connections_per_user
Hi.
This is small fix for a non-alphanumeric symbols in field names plus print real username in label.
> mysql_connections_per_user: fix for non-alphanumeric symbols in fields

- plugins/asterisk/asterisk
I apparently forgot to clear out two lines of debugging output from the
script before submitting a pull request.
Those lines of output are super useful for debugging whenever things are
not working as expected (e.g. asterisk has changed its output). So it'll
be more productive to keep them around but only output them if
MUNIN_DEBUG is set.
This is a fixup for d66fef2 which was already merged.
> asterisk: turn output into debug-only lines

- plugins/asterisk/asterisk
This adds a new graph to the multigraph so that we can now have statistics about the ConfBridge application. Since the MeetMe application has been deprecated for a long while, the graph for it is now also disabled by default, but can be brought back with a configuration option.
If the ConfBridge graph is not wanted by users, it can also be disabled by a configuration option.
> Replace meetme with confbridge

- plugins/asterisk/asterisk
This was a copy/paste error that slipped by unnoticed :\
this is hopefully my last PR for this plugin for some time
> asterisk: the confbridge graph is in the wrong category

- plugins/disk/btrfs_subvol_usage
Switch "btrfs qgroup show" for raw output format, because by default it's human readable form and can't be read later in the script.
> btrfs_subvol_usage: fix "btrfs qgroup show" output format

- templates/munstrap/templates/munin-overview.tmpl
Adds the missing bracket `[` to ensure that brackets show up after groups when hosts are grouped together.
> Add Missing Bracket

- plugins/ssl/ssl-certificate-expiry
Added support for StartTLS in _ssl-certificate-expiry_
Use 
`env.services foo.example.net_25_smtp`
to enable StartTLS on a SMTP server.
Please review this PR before commit.
> Add support for StartTLS in ssl-certificate-expiry

- plugins/router/arris-tg3442
> arris-tg3442: Remove newlines from cookie

- plugins/ping/multi_tcp_ping
By default, Net::Ping will report a good attempt even when the remote end returns "connection refused". By enabling service_check, the connection must have been established.
See https://perldoc.perl.org/Net/Ping.html#Functions
> multi_tcp_ping: enable service_check by default

- plugins/logs/loggrepx_
The pattern under which the data was saved was different than the pattern under the data was loaded on the next run. The reason being an undefined variable that evaluates to the empty string. The result was that the number of matching lines reported was for the whole logfile instead of the time since the last run.
> Fix state saving in loggrepx_ plugin

- plugins/puppet/puppetdb
It is very common for PuppetDB installs to run on a different host than
the puppetmaster. In such cases, a certificate file is normally used to
establish an encrypted communication to the server.
The most common setup for this server certificate is to use a
certificate that was signed by the puppetmaster's CA, so one would want
to verify the server cert against this same CA (it should be present on
puppet clients).
Moreover, to ensure that *only* puppet clients can communicate with
PuppetDB, a pair of client certificat/key files are usually used to
authenticate clients.
> puppetdb: implement cert validation and client cert auth

- plugins/wordpress/wordpress2
wordpress2 plugin is not working on PHP7.
* Fix the following error using PHP7 (mysql -> mysqli)
```
PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /usr/share/munin/plugins/wordpress2:112
Stack trace:
#0 {main}
thrown in /usr/share/munin/plugins/wordpress2 on line 112
```
* The previous version is still supported in this fix
```
if(function_exists('mysql_connect')) {
// less than PHP7
}else{
// PHP7
}
```
> Plugin wordpress2: add PHP7 supports

- plugins/rtorrent/rtom_allsessions_mem
- plugins/rtorrent/rtom_allsessions_peers
- plugins/rtorrent/rtom_allsessions_spdd
- plugins/rtorrent/rtom_allsessions_vol
- plugins/rtorrent/rtom_mem
- plugins/rtorrent/rtom_peers
- plugins/rtorrent/rtom_spdd
- plugins/rtorrent/rtom_vol
Aligning rtorrent rtrom_ modules same way as rtom_allsessions_ which was done in munin-monitoring/contrib#921:
In version 0.9.7 deprecated xmlrpc calls were dropped. The added files contain the needed changes for version 0.9.7+ of rtorrent.
Fixes: https://github.com/rakshasa/rtorrent/issues/757
> Remove of deprecated api calls as of 0.9.7

- plugins/system/total_by_process_
Fixed the following:
* Argument "config" isn't numeric in numeric eq (==) at line 89.
* Use of uninitialized value $ARGV[1] in string eq at line 35
> Fixed warnings generated by total_by_process_

- plugins/docker/docker_
Added parallel processing using python's muliprocessing module
to fork a new process each for each docker container when gathering
stats.
This vastly improves performance since using a for loop the script
blocks until the stats are returned.
When I ran the docker_cpu plugin without this change it would timeout. I have 43 containers running on the host in question and it would take about 90 seconds. With this improvement it takes 2-3.
> Improved docker_ performance when getting CPU/Memory stats

- plugins/router/snmp__mikrotik
Monitor temperature reported by Mikrotik routers via SNMP protocol.
PS: The multigraph approach really make easier add functionality.
> Added monitoring of Mikrotik router temperature

- plugins/http/http_request_time
Previously it would error since the $url variable is
the array key isn't the url to check it's a santized version
> Fixed autoconf on http_request_time

- plugins/postfix/policyd-spf-python
By default `policyd-spf-python` generate this output in `/var/log.mail.info`:
```
Apr 29 14:14:22 localhost policyd-spf[25915]: prepend Received-SPF: Pass (mailfrom) identity=mailfrom; client-ip=REDACTED; helo=example.com; envelope-from=example@example.com; receiver=<UNKNOWN>
```
This regex change can match also when `prepend Received-SPF` is present.
> Change regex to match "prepend" pattern in postfix/policyd-spf-python plugin

- plugins/http/http_request_time
Similar to other settings for this plugin, there is a new
env.urlN_agent setting which allows specifying a user agent
> Modified http_request_time to allow specifying a user agent

- plugins/voip/murmur_users
`split` was deprecated in PHP 5.3.0 and removed in PHP 7.0.0, `explode`
is a drop-in replacement.
> murmur_users PHP 7 support

- plugins/sensors/hwmon
Discovered thanks to an RX 570, which can show sclk and mclk via /sys/class/hwmon.
> hwmon: recognize frequencies

- plugins/disk/dm_cache_occupancy_
- plugins/disk/dm_cache_statistics_
Promox is creating logical volumes with names like `vm--100--disk--0`
> [dm_cache_] support volumes with multiple dashes

- plugins/docker/docker_
It maybe desirable to not generate stats for ephemeral containers.
This commit adds an env variable EXCLUDE which is a regex, if it matches
then the container is excluded from the cpu and memory graphs.
> Added env to exclude containers from cpu/memory docker graphs

- plugins/libvirt/kvm_cpu
- plugins/libvirt/kvm_io
- plugins/libvirt/kvm_mem
- plugins/libvirt/kvm_net
This fixes the label (vm names) for vms startet via kvm. This was tested on a host running Proxmox VE. In addition I've removed the draw parameter to unify the graphs and removed the duplicate graph from kvm_io and kvm_net.
> Improve kvm_* plugins

- plugins/zfs/zfs_list
Without this, the log gets spammed with
> 2020/08/16 04:45:24 [ERROR] In RRD: Error updating /var/lib/munin/localdomain/localhost.localdomain-zfs_list_rpool__name-quota-g.rrd: /var/lib/munin/localdomain/localhost.localdomain-zfs_list_rpool__name-quota-g.rrd: Function update_pdp_prep, case DST_GAUGE - Cannot convert '-' to float
> [plugins/zfs/zfs_list] Fixes quota für zvols. 

- plugins/systemd/systemd_units
These services are running fine, so the extinfo would mostly just clutter
the webui while making the extinfo of relevant (i.e. down) services
harder to find.
> [plugins/systemd/systemd_units] Optionally hide extinfo of active services

- plugins/user/membyuser
* Don't use a fixed scale
* Use resident set size as measure for a process' memory usage instead of vsz
* More robust username enumeration
> [plugins/user/membyuser] Minor enhancements

- plugins/user/cpubyuser
- Fix USERS=ALL only enumerating processes with a tty or pty attached
(and thus not eg. user-owned FastCGI processes, owned by eg. Apache)
- ps(1) is used to make process list parsing easier and more robust
- OTHERS_FIELD now defaults to disabled
> [plugins/user/cpubyuser] Bugfixes and enhancements

- plugins/docker/docker_cpu
This fixes an issue with docker_cpu when your container names start with integers (e.g. because you found it a good idea to prefix them with the CI_PIPELINE_ID ;-) )
munin-node output
```
155222_110_testyaml_nginx_1.cdef 155222_110_testyaml_nginx_1,1000000000,/
```
gets transfered to when calling rrd
```
...
DEF:a06259ff28d9f69b=/var/lib/munin/redacted/redacted-docker_cpu-_55222_110_testyaml_nginx_1-d.rrd:42:MAX
DEF:i06259ff28d9f69b=/var/lib/munin/redacted/redacted-docker_cpu-_55222_110_testyaml_nginx_1-d.rrd:42:MIN
DEF:g06259ff28d9f69b=/var/lib/munin/redacted/redacted-docker_cpu-_55222_110_testyaml_nginx_1-d.rrd:42:AVERAGE
...
CDEF:a27dc539c2004686=155222_110_testyaml_nginx_1,1000000000,/
CDEF:i27dc539c2004686=155222_110_testyaml_nginx_1,1000000000,/ …
```
> docker_cpu: fix data for container names starting with numbers

- plugins/git/gitlab_statistics
Graphs common GitLab statistics (user, repo, fork, ... count) using its
HTTP API statistics endpoint (requires a token to be set and passed to
the plugin)
> [plugins/git/gitlab_statistics] Added plugin to display GitLab stats

- plugins/docker/docker_
* Add support for docker_network
* Actually show non running containers counts
* Show intermediate and dangling images counts
* Add warnings on dangling images and dead containers
* Fully support autoconf and suggest
* Add graph_total to the status (thereby making the containers graph
redundant), CPU and Memory graphs
* Show most graphs as AREASTACK, this allows to get a clearer view of
both individual and total use
* Use LINESTACK1 to work around munin-contrib/munin#1343
* Include all containers in CPU/Memory/Network config, so data from
non-running containers is still displayed
* Sprinkle some info and extinfo
* Add ClientWrapper around docker module, providing caching and sorting
* Reverse-engineer author list from git log
> [plugin/docker_] Improvements to docker_ plugin

- plugins/disk/btrfs_device_stats
- plugins/disk/btrfs_device_usage
Graph the usage (in bytes and percent) and the device statistics (mainly error counters) of the devices in a btrfs pool.
I've written these plugins to scratch my own itch and have been using them for about a year now. They work great for me, but that doesn't mean they are perfect.
> [plugins/disk/] Add plugins to monitor btrfs pools on a per device base

- plugins/docker/docker_
> [docker_] Fake functools.cached_property for Python<3.8

- plugins/network/whois_
This plugin only monitors one domain per instance, but should be easily
extensible to monitor several at once if need be.
> [whois_] Plugin to monitor domain registration expiries

- plugins/ubiquiti/unifi_api
Data for UAP's is (now?) encapsulated within `stat->ap`, changed reference to reflect this change.
Also: Completely implemented handling of uninitialized values in case they do not exist (`// 0`) as suggested with #1095.
PS: I don't remember ever writting a single line of Perl-code. So for the sake of all that's holy, please double-check this pull-request! (_That being said, it seems to work on my box._)
> Fixed data for UAP

- plugins/http/http_responsecode
Just in case there is a firewall dropping packages, this plugin
would block until the plugin timeout is reached. This change introduces
the possibility to configure a much lower individual timeout.
> avoid blocking in http_responsecode

- plugins/ssl/ssl-certificate-expiry
Optional verification of request to certificate hostname match (env.checkname yes)
Optional openssl proxy usage (env.proxy PROXYHOST:PORT)
> [ssl-certificate-expiry] host name verification + proxy connection

- plugins/disk/nvme
> silly bug: writecycles must be calculated from *written* bytes

- plugins/systemd/systemd_status
Similar to systemd_units, but more states and ignores scopes and user
services. They must be allowed to fail.
> systemd_status: yet another plugin to monitor systemd status

- plugins/systemd/timesync_status
My installation of munin server (version 2.0.49) executes plugins with "fetch" command instead of an empty command line.
> Plugin timesync_status: add support for 'fetch' command

- plugins/ssl/certificate_file_expiry
It became tedious to maintain our env.CERT values so i added support for patterns to the plugin. Now it's easier to support a bunch of certs that are saved in a certain pattern (e.g. letsencrypt certs or crls for multiple vpns)
Info @wt-io-it
> certificate_file_expiry: add pattern support for CERT env variable

- plugins/disk/linux_diskstat_
The fields have changed from 11 or 15 on recent kernels but does not effect what the plugin gathers. 
See 5.4 https://www.kernel.org/doc/html/v5.4/block/stat.html versus 4.16 https://mjmwired.net/kernel/Documentation/block/stat.txt
> Update for extra fields in newer kernels

- plugins/mpd/mpdstats_
* Introduces a new environment variable to pass arguments to the `nc(1)` binary
* Uses `stats` instead of `version` in the `autoconf` call
cc @sumpfralle - thanks for #759 !
> mpdstats_ improvements

- plugins/docker/docker_
* Work around missing `total_rss` in some case (maybe cgroupv2?)
* Show and warn on unhealthy containers separately to those running
* Add a multigraph mode, to reap all the goodness of the wrapper in reducing API calls
> Docker improvements

- plugins/cpu/cpu_osx
- plugins/memory/memory_osx
Hi,
Out of the box, the munin macports package for mac osx doesn't include graphs for CPU or MEMORY, which are possibly the most useful plugins. It would be great to provide something right away after a new installation.
You may have a better idea about file organization. An idea would be to include these in the contrib repository with the file names "cpu_osx" and "memory_osx", and in the macports distribution with the plain file names "cpu" and "memory".
> cpu and memory plugins for OSX

- plugins/zfs/zpool_capacity
As per the zpool(8) man page:
> zpool list [-HgLpPv] [-o property[,property]...] [-T u|d] [pool]... [interval [count]]
>         Lists the given pools along with a health status and space usage.  If no pools are specified, all pools in the system are listed.  When given an interval, the information is printed every
>         interval seconds until ^C is pressed.  If count is specified, the command exits after count reports are printed.
> [...]
>         -p      Display numbers in parsable (exact) values.
> Use exact values in zfs/zpool_capacity#allocated

- plugins/docker/docker_
Apparently, the code support that serie, as the docs say.
This addresses https://github.com/munin-monitoring/contrib/issues/1180
> Add 'containers' to the supported series

- plugins/other/beanstalkd
- t/test-exception-wrapper.expected-failures
minimal effort to get the beanstalkd plugin work with python3 + a more modern/maintained client library.
will require `pip3 install pystalk` to work
> beanstalkd python3

- plugins/bird/bird
this is required to make the bird plugin to work with perl 5.28
> fix the bird plugin to work with perl 5.28

- plugins/disk/nvme
The default limits are sort of randomly chosen.  My nvme drives report
a warning level at 10% spare capacity, so I kept that here.
> nvme: add graph for spare capacity.  add support for limits

- plugins/gpu/nvidia_gpu_
After upgrading to nvidia drivers version 460, the output of `nvidia-smi -q` has changed, breaking the parsing script `nvidia_gpu_` at line `217`. This is due to an extra "Temperature" line being printed by `nvidia-smi -q`. This patch fixes this by grepping for the full string `GPU Current Temp`, which should be more robust and also backward compatible.
Compare this: (v450)
```
nvidia-smi -q | grep -i temp
```
```
Temperature
GPU Current Temp                  : 28 C
GPU Shutdown Temp                 : 94 C
GPU Slowdown Temp                 : 91 C
GPU Max Operating Temp            : N/A
Memory Current Temp               : N/A
Memory Max Operating Temp         : N/A
Temperature
GPU Current Temp                  : 28 C
GPU Shutdown Temp                 : 94 C
GPU Slowdown Temp …
```
> nvidia_gpu_: fix current temperature on nvidia 460

- plugins/mongodb/mongo_collection_
- plugins/mongodb/mongo_lag
- plugins/mongodb/mongodb_conn
Hi:
I'm just proposing this patch so we can have "one config line to set them all". If all scripts load the same env var, I'm using MONGO_DB_URI as there were some scripts that were already using that var name (ie: mongodb_docs).
Let me know please if you have any question.
Thanks all for your work on this project.
Cheers,
Jeremías
> Proposed update: all mongodb scripts load MONGO_DB_URI env setting.

- plugins/mongodb/mongo_collection_
- plugins/mongodb/mongo_lag
- plugins/mongodb/mongo_mem
- plugins/mongodb/mongo_ops
- plugins/mongodb/mongodb_conn
- plugins/mongodb/mongodb_docs
Hi:
I'm proposing this patch so we can configure the graphs category for mongodb scripts, as some of them were setting it as 'db', but others were using 'mongodb'.
Making it configurable I think it's the best backward-compatibility way to set them under the same category (or not) if needed.
Let me know please if you have any question.
Thanks all for your work on this project.
Cheers,
Jeremías
> Proposed update: mongodb scripts configurable graph category.

- plugins/php/php_apc.php
Fixes https://github.com/munin-monitoring/contrib/issues/1194
Detect available functions (apc_ or apcu_ ones) and call the right ones.
> Allow php_apc_ plugin to use APCu functions

- plugins/knot/knot
Sometimes after reboot munin-async + munin-node runs before knot is
ready. This will result missing knot stats, as there is no static
config in plugin. Cache results and use them instead if knot's output
is empty.
> knot: cache results, needed for first run after server reboot

- plugins/disk/btrfs_device_stats
It's always those typos!
I don't know why I didn't notice this in all those years. I had "warming" instead of "warning" all over the code. Stupid mistake!
> [plugins/disk/] Fix warning on btrfs_device_stats.

- plugins/power/nutups2_
This is needed when you monitor local and remote UPSes from single
host. You must be able to specify "ups@host" in plugin name so do
it as "ups.host".
> nutups2_: "@" is invalid character in plugin name so use "." instead

- plugins/lxc/lxc_guests
The cgroup data was (yet again) moved to a new location in recent LXC
releases, starting with v3.1.0 from what I could gather.
https://github.com/lxc/lxc/issues/2782 states:
> [The cgroup lxc.payload] exists to adhere to cgroup2 delegation requirements.
> LXC v3.1 compatibility

- plugins/docker/docker_
docker_ plugin sanitized container names when printing config but
not values which led to a disparity resulting in no data on graphs
for all containers whose names are subject to sanitization. (#1212)
> docker_: sanitize value container names

- plugins/redis/redis
Previously it returned "yes" and empty graph with all labels having
value "0". Also remove bogus "multigraph redis" line.
TODO: die() in get_conn() makes this plugin to fail if any Redis
instance can't be connected.
> redis: fix "autoconf" to return "no" if no instances are configured

- plugins/power/nutups2_
"upsc name" can output line "input.transfer.reason: " (key without value).
Allow it.
> nutups2: fix for status line without value

- plugins/amavis/amavis_multi
Here's unified, updated and rewritten plugin of my PR #1139.
Two comments:
1) This plugin includes all **useful** data from amavis, and it's easy to add more if there's some ideas. Therefore I'm happy to rename this plugin as "amavis", dropping "_multi", if that's ok?
2) This plugin includes all the info that other plugins (amavis_, amavis_awk, amavis-debian) provide, plus more, all in single multigraph plugin. Other access amavis's db directly (bad, can change) or parse it from log (bad, lot of cpu time). Amavisd-agent was created to provide all that info.
> amavis_multi: multigraph plugin to monitor amavis mail filter

- plugins/docker/docker_
This PR just fixes the issue (https://github.com/munin-monitoring/contrib/issues/1228).
The commit (https://github.com/munin-monitoring/contrib/commit/a3ae1af155e2fa07b3c8b97fd7e538935b059705) removed the method `client.containers` and didn't changed/removed all dependencies of the script.
> Fix for docker_containers

- plugins/bind/bind9_resolver_stats
- plugins/bind/bind9_server_stats
- plugins/bind/bind9_socket_stats
previously only stat_file would only be used for data cleanup not for
fetching the data. also fixed some shellcheck warnings.
This fixes the following problem:
If you configured `stat_file` to be `/var/run/named/named.stats` like this:
```
[bind9_*]
env.stat_file /var/run/named/named.stats
```
and enabled writing statistics with `statistics-file "/var/run/named/named.stats";` in bind9
you got the error `cat: /var/cache/bind/named.stats: No such file or directory` when running the plugin.
With this fix stat_file is also considered for `cat` not only for `rm`.
I fixed some shellcheck stuff in the affected files as well, but didn't want to change too much for a simple bugfix (e.g. there is still unecessary cat uses, chaining of seds and some other stuff in there).
Info @wt-io-it
> bind9_*_stats: fix using env variable stat_file

- plugins/gpu/nvidia_gpu_
Today, I noticed that my recent PR for Rx/Tx throughput outputs #1226 does not give correct readings on systems with multiple gpus.
The problem is that the multiplication `$((valueGpus*1024))` does not work for unseparated input values (as returned by the echo-grep-cut combo). The result is unscaled data being processed by munin - therefore showing kilobits per second as bits per second.
Here is a fix for that! The code replicates the loop already found under `mem)` (lines 250-259).
Sorry for having overlooked this issue.
> nvidia_gpu: fix units of Rx/Tx throughput (multiple gpus)

- plugins/rtorrent/rtom_vol
Since there are no associated values for 'hashing', 'seeding', and
'active', a warning is seen in munin-update.log every time this plugin
is fetched.
> rtom_vol: remove unused config parameters

- plugins/torrent/deluge_
Version 1.0.0 of this plugin requires version 1 of Deluge. Deluge 2 was released in June 2019.
This commits bumps the plugin to version 2.0.0.
This plugin has three modes. The modes "bandwidth" and "states" are working equally to the previous version.  The third mode, "connections", is changed.
The connections mode previously printed one value: the total number of connections.  That RPC call is removed in Deluge 2, and I'm instead using `get_session_status`, which delegates the call to libtorrent's [session statistics function](https://libtorrent.org/manual-ref.html#session-statistics). libtorrent is better documented, so it's easier to work with compared to Deluge.
"Number of peers" replaces the previous "number of connections", and I've added half open peers, and peers interested in …
> Update the Deluge plugin to handle Deluge 2.x

- plugins/solar/fronius
"round" is part of jq's math support. Some distros (rhel8) don't enable it.
Fortunately round can be emulated with "floor" which is always present in
modern jq.
> fronius: support jq builds without math library

- plugins/zfs/zfs_list
zfs list might list thousands of transient snapshots if `zpool
listsnapshots=on` and something like zfs-auto-snapshot is used.  It's
also not useful to graph them since they're unchanging in time, and
the parent volume is graphed anyway.  Limit zfs list to
"filesystem,volume" instead of "all" including snapshots
> zfs list -t filesystem,volume to suppress snapshots

- plugins/chrony/chrony_status
Was not expecting #1255 to be merged so quickly 🤪. Now the new serverstats graph has been fully tested and actually works 😉.
This change also doesn't needlessly convert all values to floating point numbers, instead provides the values to munin in the same format as they are originally output by chrony.
Also this adds some server stats found in chrony 4.0 (but still works with 3.4 and probably earlier).
> chrony_status: fix fetch output for serverstats graph

- plugins/munin/munin_events
in 56cd2c926ca99e396a0b6c2ebee76394bb4de195 `&> /dev/null` was converted
to posix in an invalid way, should have been `>/dev/null 2>&1`
this prevents the plugin dumping the logs to stderr at the end after printing the values
Info @wt-io-it
> munin_events: fix plugin having too much output

- plugins/router/mikrotik_system
The file wasn't executable for which munin-run complained:
```
$ munin-run mikrotik_system
```
> fixed file mode of mikrotik_system + added that it was tested on RB493G

- plugins/ssh/sshd_log
Allows for configuring either general or specific warning or critical
levels, or any combination of that.
This is backwards compatible, since it doesn't change a thing to
the output, unless specific variables are specified.
> [sshd_log] Allow for configuration of warning and critical levels

- plugins/ssl/certificate_file_expiry
Scale values were "4e+01, 5e+01, ...". Using linear scale and "48, 50, 52, ..." is much more readable.
Also use shorter vlabel, old one is too long.
> certificate_file_expiry: label "50" instead of "5e+01"

- plugins/bind/bind95_
This prevents `bind95_` from displaying `-nan` for counters not yet present in stats file (not requests yet) and instead displays them as 0. It makes sure that there is a value for all counters defined in `bind95_ config`.
Info @wt-io-it
> bind95_: report 0 values for not found lines

- plugins/ssl/certificate_file_expiry
logarithmic was removed in d885a314ade7c1287237d61f4d2b1f24db509533
but still has it's benefits for openvpn CA and CRL certs. when enabling
logarithmic we keep the SI units now instead of rrdtools default
scientific notation.
This enables using logarithmic graph as an option again that was removed in #1266.
Info @wt-io-it
> certificate_file_expiry: optional logarithmic view for long lived certs

- plugins/disk/btrfs_device_usage
During certain situations, a device in the btrfs pool can show a total
capacity of 0 bytes. This is aspecially true when replacing or removing a
failed disk.
This fix stops the plugin from crashing in that situation but just report
the devices percentage as unknown (U). That way other devices in the pool
stil can be monitored.
> [btrfs_device_usage] fix division by zero when btrfs pool is unhealthy

- plugins/git/gitlab_statistics
Fix the error `AttributeError: module 'urllib' has no attribute 'request'` and then the error `TypeError: the JSON object must be str, bytes or bytearray, not HTTPResponse` by reading and decoding the urllib request.
> [gitlab_statistics] Fix urllib request decoding

- plugins/minecraft/minecraft-users-ram_
Fixes:
- Make playercount work on non english systems
- Avoid getting an invalid PID if not run with sufficient permissions
- Fix getting CPU usage
Enhance:
- Clearify that CPU usage is in percent
> [minecraft-users-ram] Fix several bugs in plugin minecraft-users-ram_

- plugins/router/arris-sb6183
When error counts wrap they are displayed as int32 and negative.
Recast them to uint32 to fix math.
Signed-off-by: Nathaniel Clark <Nathaniel.Clark@misrule.us>
> arris-sb6183: Fix int32 wrapping in WebUI

- plugins/ssl/ssl-certificate-expiry
This fix allows to skip validity checks on any intermediate certificate
which subject hash appears in the list.
Let's Encrypt certificates are cross-signed by both DST Root CA X3 and
ISRG Root X1. DST Root CA X3 has expired on 2021-09-30 [0], which causes
the plugin to incorrectly report some full-chain LE certificates as
expired.
[0] https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/
> [ssl-certificate-expiry] add env.skip_cert_hashes to skip certificates

- plugins/weather/wunderground_
The data was incorrectly loaned from a `temp` subgraph, which should
have been `temperature`.
This led to errors during munin-graph, as follow
[ERROR] Failed to find windChill source at temp.windChill, skipping field
[ERROR] Failed to find heatIndex source at temp.heatIndex, skipping field
[PERL WARNING] Use of uninitialized value in concatenation (.) or string at /usr/share/perl5/Munin/Master/Utils.pm line 1149, <GEN1> line 1728.
[ERROR] filename is empty for $VAR1 = {
'#%#name' => 'windChill',
'graph_data_size' => 'normal',
'label' => 'Wind chill [Â°C]',
'update_rate' => '300'
};
, temp.windChill
[PERL WARNING] Use of uninitialized value in concatenation (.) or string at /usr/share/perl5/Munin/Master/Utils.pm line 1149, <GEN1> line 1728.
[ERROR] filename is empty for $VAR1 = {
'#%#name' …
> [wunderground_] Fix windChil and heatIndex in root graph

- plugins/exodus/exodus_
This plugin monitore number of applications, reports and trackers of an [Exodus](https://github.com/Exodus-Privacy/exodus/) instance.
This plugin is based on [the Exodus API documentation](https://github.com/Exodus-Privacy/exodus/blob/v1/doc/api.md) and can be used with any Exodus instance starting from [version 1.25.0](https://github.com/Exodus-Privacy/exodus/releases/tag/v1.25.0).
> [exodus_] Add plugin to monitore number of applications, reports and trackers

- plugins/ubuntu/apt_ubuntu
Half a package can't be updated, so make the graph display integers instead of floats that always end in `.00`
> Update apt_ubuntu to display integers instead of floats

- plugins/ssl/certificate_file_expiry
This enables monitoring certificates for openvpn where the client has the certificates defined directly in the client.conf
as described in the openvpn manual https://community.openvpn.net/openvpn/wiki/Openvpn23ManPage#lbAV
Also i restored the default warning and critical level, i accidentially removed in https://github.com/munin-monitoring/contrib/commit/76170d27453f4b2df4e42a6445a6f2be5589213a
Info @wt-io-it
> certificate_file_expiry: enable monitoring inline openvpn certificates

- plugins/nginx_unit/nginx_unit
Value "2.34M seconds" doesn't mean anything  but "27 days" does.  Use days for process age.
> nginx_unit: use more human readable scale

- plugins/chrony/chrony
If we don't want to show any host names in graphs/legend, it makes sense to not resolve them.
I occasionally notice the issue with name resolution of IPv6 addresses on certain networks, which makes `chronyc tracking` take 20+ seconds. Adding -n makes it almost instantaneous.
> chrony: don't resolve IP addresses to hostnames

- plugins/system/linux_psi
- plugins/system/pressure
Adds a plugin to monitor the pressure stall information (psi) as reported by the Linux kernel.
- groups averages per resource
- rate/derive totals for ease of reading
- resources, intervals and scopes configurable
See: https://www.kernel.org/doc/html/latest/accounting/psi.html
I've written this plugin because I read about the metric and wanted to get a feel for what's "normal" on these values. Therefore I did not include any warnings and am not certain that all metrics are actually useful. For example I'm not sure if it helps to monitor the 10 and 60 second averages long term. So I made this stuff configurable. Still this might help someone else, or someone has an idea on an improvement. So here it is for everyone to use.
> [system/pressure] Add plugin to monitor pressure stall information (psi)

- plugins/router/mikrotik_system
Hi,
with the latest versions of RouterOS some Names have changed.
That PR fixes the Errors for "temperature" and "voltage".
It is tested on RB5009, hex, CRS309, CRS305 with RouterOS 7.2.1. It is NOT tested with older Versions of RouterOS because i dont have any devices left with it.
> Fix mikrotik_system -  temp + voltage

- plugins/ircd/irc2
- Add port support (defaults to `6667`)
- Add SSL/TLS support (defaults to `0`)
- Add IPv6 environment variable
- Improve documentation
- Remove `host_name` config to avoid localhost IRC monitoring limit
> [irc2] Add port and SSL/TLS support, add IPv6 env variable

- plugins/network/smtp_hello_
This contains the following improvements:
* enable running the plugin with bash time keyword if time executable is not found
* enable using curl with a proper SMTP client implementation instead of `echo | nc` to enable monitoring servers that do not automatically terminate the connection after `HELO localhost` is answered.
* enable configuring the SMTP test command (e.g. to `QUIT` or `HELP`)
* enable configuring warning and critical levels
* check status when using curl to detect if mailserver is not responding as expected / not connectable
* enable monitoring multiple ports on one host and ports different from 25
Info @wt-io-it
> smtp_hello_ improvements

- plugins/disk/du-2
when installing / first running the plugin, it can take longer than
one munin-update call to create the $TIMEFILE. so until it is created
we assume the $LOCKFILE is not too old yet and let the first run finish
before we spawn additional processes.
On one of our systems we run munin-node in a docker-container and it started to consume more and more memory / cpu and disk io until the system started the oom killer. This seems to happen when du-2 takes a long time to complete and you start with a fresh installation where the file containing the last cache update timestamp is not yet created.
Info @wt-io-it
> du-2: fix resource consumption when first running the plugin

- plugins/puppet/puppet_runtime
`perlpod` needs these blank lines in order to detect and format the documentation.
> puppet_runtime: fix perlpod

- plugins/libvirt/kvm_cpu
- plugins/libvirt/kvm_io
- plugins/libvirt/kvm_mem
- plugins/libvirt/kvm_net
fixed graph failure for VM names starting with digits
used "Validate filednames" Python stanza from docs to improve
clean_vm_name functions, helping graph creations for VM with names
starting with digits, like "150-121-Apache".
remember: each data source in a plugin must be identified by a field
name (in this case VM names). The characters must be [a-zA-Z0-9_],
while the first character must be [a-zA-Z_].
> kvm_*: improve field names

- plugins/clamav/clamav
Add `exit 0` at the end, otherwise the plugin fails
> Fix for clamav plugin

- plugins/dovecot/dovecot_stats_
Dovecot has a new "stats" command, and the version that this plugin works with is now called as "doveadm oldstats", so try to adapt the command based on the dovecot version.
Fixes #1327
> Allow dovecot_stats_ cope with Dovecot 2.3

- plugins/router/arris-sb6183
Corrected ```multi_graph``` to ```multigraph```.
> Correct multigraph typo for uptime graph (arris-sb6183)

- plugins/prosody/prosody_0.12_
This plugin replace `prosody_` for Prosody versions 0.12+.
But it's just an "as is" replacement, a better idea would be to create an [OpenMetrics](https://prosody.im/doc/modules/mod_http_openmetrics) Prosody plugin.
Because Prosody change the output format of commands used in the previous `prosody_` plugin.
Because with this plugin you don't need to enable any other module, like with the previous version.
I think about it and I prefer to write a new plugin for more readability and simplicity.
For future improvements: maybe someone will write a new graph with IP types (IPv4 vs IPv6) or CSI states, so all is ready to do it.
> [prosody_] Add prosody_0.12_ plugin for Prosody version 0.12+

- plugins/ssl/ssl-certificate-expiry
This should help with unreachable hosts, as the plugin can take more than 10 minutes to complete otherwise. These changes should be fully backwards compatible, since the default is no timeout set, so it acts the same way as before if not explicitly configured otherwise.
Also I took the freedom to disable shellcheck SC1090. When linting this script, this will always fire. This is because shellcheck only does static code analysis and thus can not determine dynamic filepath for includes.
Changes:
- Introduce "timeout" configuration
- Only run timeout when configured
- Document usage of new configuration
- Disable shellcheck SC1090
> [ssl/ssl-certificate-expiry] Add configurable timeout

- plugins/disk/raid2
LSI MPT Fusion SAS 3.0 RAID status can be read from /sys files. Also includes minor coding style fixes.
> raid2: add support for LSI MPT Fusion SAS 3.0 RAID

- plugins/imapproxy/imapproxy_multi
- Added imapproxy.conf as parameter as pimpstat won't work without
- Added unversal_newlines as Popen parameter because otherwise it's binary output
> Fix imapproxy_multi

- plugins/router/arris-sb8200
This actually silences InsecureRequestWarning.
The Arris SB8200 has 32 downstream channels, but in my experience report more than that, but the "extra" channels report modulation as "Other" instead of QAM256.  This filters those channels, since they seem to drive the error count up, but don't provide data.
> [arris-sb8200] Fix channel selection and warnings

- plugins/lighttpd/lighttpd_
Default for Python 3 is to return byte-objects, not string. This will cause the plugin to fail with an error: "TypeError: a bytes-like object is required, not 'str'". Fixed by decoding for UTF8.
> Fix for Python 3

- plugins/docker/docker_cpu
Enable using docker_cpu on systems with cgroup v2 (fresh server install with Ubuntu 22.04.2 LTS) where /sys/fs/cgroup/cpuacct/docker/ is not available.
Info @wt-io-it
> docker_cpu: handle cgroup v2

- plugins/proxmox/proxmox_vm_count
This PR set the graph options to output only integers because you cant have 1.3 VMs running. ;-)
> proxmox_vm_count: Integers

- plugins/docker/docker_memory
Enable using docker_memory on systems with cgroupv2 (in our case Ubuntu 22.04.2 LTS) where /sys/fs/cgroup/memory/docker/ is not available.
Should have checked this right away after #1358 but only noticed it today.
Info @wt-io-it
> docker_memory: handle cgroup v2

- plugins/solar/solarman_api_inverter
Remove unneccesary AppId, it is only used while obtaining the token.
`Only the request token url needs to pass the APPID, other interfaces do not need to pass the APPID in the request url.`
> Deye/Solarman: remove AppId variable

- plugins/zfs/zfs_pool_dataset_count
This PR set the graph options to output only integers because you cant have 1.3 datasets/pools. ;-)
> zfs_pool_dataset_count: Integers

- plugins/icecast/icecast2_stats_
- Fix sources parsing if only one source is available (without array)
- Keep parsing loop the same if there is more than one source (with array)
By default with Icecast2, when more than one source is available `["icestats"]["source"]` is an array of dict (each dict is a source) but when only one source is available `["icestats"]["source"]` is just a dict with the single source values.
This change check if `["icestats"]["source"]` is a dict or not to make an appropriate parsing choice.
> [icecast2_stats_] Fix sources parsing if there is only one source

- plugins/disk/md_iostat_
Doesn't work with '--write-mostly' drives like sde1 in : 
```
md94 : active raid1 sde1[1](W)(S) sdd1[2]
```
I assume to remove everything behind the opening bracket
> Update md_iostat_ for '--write-mostly' drives

- plugins/rabbitmq/rabbitmq_consumers
- Fix rabbitmqctl output filter to avoid bad values
By default `rabbitmqctl list_queues -p / name consumers` give this kind of output:
```
Timeout: 60.0 seconds ...
Listing queues for vhost / ...
name	consumers
celery	1
```
Then in this plugin it result to:
```
Timeout:.value 60.0
name.value consumers
celery.value 1
```
The `consumers` value generates the following error message:
```
[ERROR] In RRD: Error updating /var/lib/munin/production/server1-rabbitmq_consumers-name-g.rrd: /var/lib/munin/production/server1-rabbitmq_consumers-name-g.rrd: Function update_pdp_prep, case DST_GAUGE - Cannot convert 'consumers' to float
```
This merge request fix the grep command to get this plugin result:
```
celery.value 1
```
> [rabbitmq_consumers] Fix rabbitmqctl output filter

- plugins/rabbitmq/rabbitmq_messages
- plugins/rabbitmq/rabbitmq_messages_unacknowledged
- plugins/rabbitmq/rabbitmq_messages_uncommitted
- Fix rabbitmqctl output filter to avoid bad values
Like #1323 
By default `rabbitmqctl list_queues -p / name messages` give this kind of output:
```
Timeout: 60.0 seconds ...
Listing queues for vhost / ...
name	messages
celery	0
```
Then in this plugin it result to:
```
Timeout:.value 60.0
name.value messages
celery.value 0
```
This merge request fix the grep command to get this plugin result:
```
celery.value 0
```
> [rabbitmq_messages*] Fix rabbitmqctl output filter

- plugins/disk/nvme
Hi.  All other graph titles in this module are prefixed with 'NVME' except this one, which was added later on.  My patch change the titles to make them consistent.  Thank you!
> nvme: Prefix 'NVME' to spare graph title for consistency.

- plugins/disk/nvme
Fixes https://github.com/munin-monitoring/contrib/issues/1373
Tested on Ubuntu 23.04 and Debian bookworm (both using nvme client 2.3) and Ubuntu 22.04 (still using nvme client 1.6)
Info @wt-io-it
> nvme: fix for nvme-cli > 2

- plugins/weather/weather_hum_
- plugins/weather/weather_press_
- plugins/weather/weather_temp_
This fixes a few bugs in the noaa.gov based weather plugins and adds a new one for humidity.
There was an issue with the read function of urllib returning an object, which got handled as a string afterwards. This caused issues:
```
Traceback (most recent call last):
File "/tmp/weather/./weather_press_LOWW", line 43, in <module>
hpa = re_hpa.findall(txt)[0]
TypeError: cannot use a string pattern on a bytes-like object
```
While implicit string casting might work, it's better to do so explicitly. This avoids said bug.
There was another bug in the temperature plugin, that didn't occur every time. It caused the temperature be set to the same value as the dew point. Turned out that, for some reasons, linebreaks were handled differently from time to time. Improving the RegEx to be more specific …
> [weather_press/temp/hum_]: Bugfixes in noaa based plugins and add humidity

- plugins/varnish/varnish
- Fix json values fetch
- Remove old or deprecated fields
- Fix renamed fields
- Fix `get_values()` json (now values are in `counters`)
- Remove `SMF`
- Remove `SMS`
- Remove `backend_toolate` ([deprecated](https://github.com/varnishcache/varnish-cache/issues/1726))
- Replace `sess_drop` by `sess_dropped`
- Replace `sess_pipe_overflow` by `sc_pipe_overflow`
> [varnish] Fix varnish plugin for varnishstat output

- plugins/ntp/ntp_packets
Debian bookworm ships the **_ntpsec_** daemon which uses an other output format for the _ntpq_ stats command. 
Support for this new output format was added. Also some pep8 related cleanup was performed.
Testing was done on Debian bookworm and bullseye (which uses the old implementation via **_ntpd_**)
> [ntp_packets] add support for ntpsec

- plugins/knot/knot
Plugin will graph these optional Knot modules only if they are enabled.
> knot: add support for mod-cookies and mod-rrl statistics

- plugins/power/nutups2_
Wrong format for setting the environment for critical and warning thresholds.  Adjusted and tested via making sure limits are updated in config run of `nutups2_powershield-commander_voltage config`
```ini
[nutups2_powershield-commander*]
env.battery_critical 20.8:27.5
```
> documentation fix for critical threshold for nutups2_ plugin

- plugins/router/freebox
It seems the default base URL stopped working, so a locally-resolvable
address or name needs to be provided instead.
> [router/freebox] Allow to override the default base URL

- plugins/dhcp/kea
I changed read_data's return value after testing autoconf. Oops...
> kea: fix autoconf, it always returned "yes"

- plugins/cpu/process_group
Plugin printed wrong values if multiple groups were defined.
> process_group: fix bug caused by auto-indent

- plugins/chrony/chrony_status
After reboot stratum is 0 for a very short period of time. Convert it to U. Include unknown_limit to config to not send warning email.
I finally found a server where this workaround was needed.
> chrony_status: fix reboot-workaround, value is str not int

- plugins/power/tasmota_
Outputs current switch state for tasmota switches (including multi switches if present) and tasmota dimmers (including multiple channels if present)
> Add switch and dimmer state capability for tasmota plugin

- plugins/quake/qstat
- Check script with [ShellCheck](https://www.shellcheck.net/)
- Check for valid $ip and $port (and not only $gametype) before collecting stats
- Add variable `bot_prefix` to enable counting bots by prefix (and not only `0ms` ping time). This is especially needed for source engine games (i.e. cstrike)
- Draw nicer graph with AREASTACK (and not LINE). Aareas are a better way to represent slots filled by actual players or bots.
- Split counting of bots and players (Bots were part of playervalue before)
> [qstat]: Some enhancements (ShellCheck fixes, script fixes, bot_prefix variable, nicer graph with AREASTACK)

- plugins/pdns/pdns_rel
Fix the condition to not return any values when there were no queries to the server since the last call. Return a 0 as cache hit rate in that case.
> Fix pdns_rel to always have correct output

- plugins/network/if1sec-c.c
Compilers warn that "`%llu`" doesn't match the `uint_fast64_t` type for all machines.
These are just being `sscanf()`'ed to be `sprintf()`'ed a few lines later, there's no need for performance.  These can just be vanilla "`unsigned long long`"'s to match the existing format specifiers.
Example of compiler warning:
```
if1sec-c.c: In function 'acquire':
if1sec-c.c:189:38: warning: format '%llu' expects argument of type 'long long unsigned int *', but argument 4 has type 'uint_fast64_t *' {aka 'long unsigned int *'} [-Wformat=]
189 |                         sscanf(line, "%s"
|                                      ^~~~
......
195 |                                 , &r_bytes, &r_packets, &r_errs, &r_drop, &r_fifo, &r_frame, &r_compressed, &r_multicast
| …
```
> network: Fix sscanf format warnings

- plugins/nextcloud/nextcloud_
After nextcloud version 28 the installed and updateable apps aren't listed anymore by default in serverinfo, see https://docs.nextcloud.com/server/stable/admin_manual/release_notes/upgrade_to_28.html#monitoring
The documentation says _However, please do not check this endpoint too often._. Presuming that every five minutes is _not too often_, appending `&skipApps=false` to the `API_PATH` is including the apps information again.
> Fix for checking installed and updateable apps

- plugins/wireguard/wireguard_
Enhancing the wireguard_ plugin in Munin by adding active peer information based on the latest handshake timestamp. This addition provides insights into ongoing connections. The decision to use a 10-minute interval balances the need for accuracy with minimizing data fluctuations. This enhancement improves monitoring capabilities and contributes to a more comprehensive overview of WireGuard activity.
> Adding active peer information into wireguard_ plugin

- plugins/disk/nvme
On my Ubuntu 23.10 the Namespace in `nvme list` is now prefixed with 0x.
`nvme --version`: nvme version 2.5 (git 2.5)
Info @wt-io-it
> nvme: fix handling namespaces prefixed with 0x

- plugins/varnish/varnish
- Move warning configurations in environment variables
- Warning variables added : 
- `backend_unhealthy_warning`
- `threads_destroyed_warning`
- `threads_failed_warning`
- `threads_warning`
- By default warning values are not added without environment variables set
> [varnish] Move warnings in environment variables

- plugins/nginx/nginx_vhost_traffic
Otherwise:
```console
$ ./nginx_vhost_traffic
./nginx_vhost_traffic: 38: Bad substitution
```
> nginx_vhost_traffic: Fix typo aggregate

- plugins/docker/docker_cpu
Enable detecting ncpu (number of cpus the container can use) from cgroup (v2) cpu.max. This is set when limiting the number of cpus with docker compose:
```yaml
services:
service_name:
...
deploy:
resources:
limits:
cpus: "1.0"
```
And enable defining warnings for containers using too much CPU. As a follow up to be able to check for bugs like this: https://gitlab.isc.org/isc-projects/bind9/-/issues/4656
Info @wt-io-it
> docker_cpu: enable configuring warnings for cpu usage

- plugins/disk/nvme
the previous commit 2eab6784c052335efa1a58c97ce2827970dbf2fc introduced an issue because it used a capturing group for 0x. All groups after this were off by one then and the usage always reported as 0.
Unfortunately i only noticed this today because a few servers i have a warning when nvme reported usage is 0.
Info @wt-io-it
> Fix nvme always reporting 0 usage.

- plugins/synapse/synapse_
This is a fix for https://github.com/munin-monitoring/contrib/pull/1433. Don't count bots having a `null` value of `last_seen_ts`. Fix comparing possible empty `$REPORTS` variable.
> [synapse_] Fix for last PR (fix counting puppets)

- plugins/disk/gluster
Change value from "current absolute value" to "15min average value" and tune warning limits accordingly. Healing value can sometimes be 1 and gluster will fix it by itself. Send warning only if it stays at 1 (or above) for 15 minutes. This will still send a warning immediately if it goes to 3 or above.
> gluster: don't send warning for self-healing errors if they get fixed

- plugins/ssl/letsencrypt_weekly
Enable specifying `letsencrypt_dirs` to be able to monitor different / multiple directories.
This is useful when having the certificates in a docker volume used by docker containers without sharing those directories in /etc/letsencrypt/.
Info @wt-io-it
> letsencrypt_weekly: enable monitoring multiple directories

- plugins/systemd/systemd_units
- Avoid missing failed units
`--plain` argument print unit dependencies as a list instead of a tree and avoid showing sometimes colored dot.
This dots are displayed to identify failed units but messed with the awk command, so this failed unit is never seen. With this `--plain` argument, dots are not displayed anymore.
This example use 3 services: 2 active (`dovecot` and `postfix`) and 1 failed (`fail2ban`).
```
$ sudo systemctl --no-pager --no-legend --all | grep -E "dovecot.service|fail2ban.service|postfix.service" | awk '{print $1, $3}'
dovecot.service active
● loaded
postfix.service active
```
```
$ sudo systemctl --no-pager --no-legend --plain --all | grep -E "dovecot.service|fail2ban.service|postfix.service" | awk '{print $1, $3}'
dovecot.service active
fail2ban.service failed …
```
> [systemd_units] fix missing failed units

- plugins/power/tasmota_
I introduced a quoting error in f1e354eb, particularly '$axis'.  Formatting of all similar lines changed so I don't do it again.
> tasmota: introduced incorrect escaping in f1e354eb

- plugins/nginx/nginx_error
Enable supporting different log formats by giving a custom awk script to get status code from different columns or patterns.
info @wt-io-it
> nginx_error: support custom log format with awk scripts

- plugins/tesla/tesla_wall_connector_
This allows for monitoring multiple Tesla Wall Connectors.
> tesla_wall_connector: convert to a wildcard plugin

- plugins/libvirt/kvm_cpu
- plugins/libvirt/kvm_io
- plugins/libvirt/kvm_mem
- plugins/libvirt/kvm_net
fixed graphing failures for VM deployed on legacy Centos 6.9 virtualization
platforms (script uses the Proxmox entries), in the case of VM domain names
beggining with digits (first field name character must be [a-ZA-Z_])
used "Validate field names" Python stanza from documentation ("How to write
plugins", "Notes on field names") to improve the clean_vm_name function, thus
munin kvm graph creation succeeded for VM with names starting with digits,
like "150-121-Apache", deployed on Centos 6.9 virtualization platforms.
> kvm_*: improve field names for Proxmox, Centos

- plugins/php/php_apc.php
The `php_apc` plugin accesses `http://localhost/php_apc.php?act=percents` .
When APC has no statistics for hits and misses (e.g., right after the server starts up), a `DivisionByZeroError` is raised:
```
PHP Fatal error:  Uncaught DivisionByZeroError: Division by zero in /var/www/html/php_apc.php:32
```
This pull request fixes the `DivisionByZeroError` by ensuring the denominator is validated when APC has no statistics.
> php_apc: fix DivisionByZeroError when hits + misses = 0

- plugins/synapse/synapse_
We recently deactivated a lot of puppet users on our matrix-synapse and there were some wrong numbers ... This patch fixes this and makes the variables a little bit readable.
> [synapse_] Some fixes and clearer variables

- plugins/gpsd/gpsd.c
The graphs are basically identical to the original Ruby plugin, but there is no longer a dependency on the "gpspipe" utility; a direct TCP connection to gpsd is established, and the JSON is parsed using the json-c library.
The intent here is to provide the same functionality on systems that are resource-constrained and/or sensitive to jitter (e.g., an embedded NTP server).
This can be compiled like such after editing GPSD_HOST / GPSD_PORT:
gcc -o gpsd gpsd.c -ljson-c
> gpsd: add C rewrite

- plugins/solar/sun2000_
Please add 1059e3a4d8474cb4f723ed05c5eb853d14175cac (Hyundai sun2000 solar inverter stats) to contrib.
> SUN2000 solar inverter and battery stats

- plugins/gpu/nvidia_gpu_
The utilization used to be on a line beginning with "Gpu", but has since been capitalized to "GPU". There's already several other instances of that in the nvidia-smi output, so narrow down the search by returning only the line after "Utilization".
> nvidia_gpu_: fix utilization when using 570.x driver

- plugins/wireguard/wireguard_
In case of peers that have never been connected, the output of `wg show {iface} dump` is something like this
aAbBcCdD=   eEfFgGhH=   (none)   10.0.0.15/32   0   0   0   off
aAbBcCdD=   eEfFgGhH=   (none)   10.0.0.16/32   0   0   0   off
aAbBcCdD=   eEfFgGhH=   (none)   10.0.0.17/32   0   0   0   off
The repeated `(none)` in many lines break the charts image to be created.
This PR excludes `(none)` from the list of peers.
> [wireguard_] Prevent never-connected peers to be shown as "(none)"

- plugins/docker/docker_
When there aren't any volumes then extinfo wont have any content, which causes a line error to be logged in munin-update.log. This fix ensures that extinfo will be set to a dash when no volumes exists
> fix(docker_): set empty extinfo value to '-' when no volumes exists

- plugins/sensors/turbostat_
The `turbostat_exists` function should always be called as it 1) sets the default executable path  and 2) ensures that turbostat is really executable and returns meaningfull data
> fix(turbostat_): always check turbostat exists and is executable

- plugins/wireguard/wireguard_
> ⚠️ This PR contains a breaking change, installing it will recreate/reset all existing wireguard graphs
Basically a rewrite of the wireguard plugin.
The wireguard plugin is currently using the endpoint as a unique identifier for peers. Not sure why I ever thought that was a good idea, because besides that that field returns `(none)` for not connected peers (as found by @droscy in #1487) it will also change every time a warrior client changes its location.
The only field  that is guaranteed to be unique & present is the public key, so this PR changes that graph ids are using the public key. This also fixes the problem from #1487.  The endpoint is still used as label for graphs, not sure if that is the best option? Let me know if anyone has suggestions.
Also add dirtyconfig support & some …
> fix(wireguard_): use public key as graph id's as those are required and unique

- plugins/nextcloud/nextcloud_
When running the `nextcloud_` plugins for multiple nextcloud instances, you can easily hit the rate limit for the app updater check. This fix allows to disable checking for app updates on certain instances.
> [nextcloud_]: Allow to disable check for app updates

- plugins/prosody/README.md
- plugins/prosody/prosody_openmetrics
Add message encryption status based on [`mod_measure_message_e2ee`](https://modules.prosody.im/mod_measure_message_e2ee.html) Prosody module.
This PR also fix some mistakes:
- Add prefix_table
- Fix filter_metric function for family_end
- Rename config_table to label_table
> [prosody_openmetrics] add message_encryption_status

- plugins/gpu/nvidia_gpu_
Fixes #1509 which causes a divide by zero when multiple GPUs are in use since the usedMemGpu and totalMemGpu variables contain multiple values. This fix uses cut to split the fields when multiple GPUs and ensures there is only one value in each. It also makes the grep for the memory information more specific to look for the string "FB Memory Usage" which returns only a single entry instead of "Memory Usage" which returns two (one of which is always zero). 
I have tested this on a single GPU P100, dual GPU P100 (both running nvidia-smi version 575.51.03) and a quad GPU A100 system (running nvidia-smi version 575.57.08).
> Fixes bug with multiple GPU systems causing a divide by zero.
